insert into Company (idCompany, name, area) values (1, 'Ferry-Skiles', 'Engineering');
insert into Company (idCompany, name, area) values (2, 'Steuber-Lynch', 'Research and Development');
insert into Company (idCompany, name, area) values (3, 'Gottlieb Group', 'Support');
insert into Company (idCompany, name, area) values (4, 'Kirlin-Kunze', 'Business Development');
insert into Company (idCompany, name, area) values (5, 'Hirthe, Zulauf and McCullough', 'Legal');
insert into Company (idCompany, name, area) values (6, 'Schmidt and Sons', 'Research and Development');
insert into Company (idCompany, name, area) values (7, 'Roberts-Predovic', 'Accounting');
insert into Company (idCompany, name, area) values (8, 'Haag-Hodkiewicz', 'Product Management');
insert into Company (idCompany, name, area) values (9, 'Ondricka-Bode', 'Research and Development');
insert into Company (idCompany, name, area) values (10, 'Collier, Wuckert and Beatty', 'Product Management');
insert into Company (idCompany, name, area) values (11, 'Durgan-Abshire', 'Sales');
insert into Company (idCompany, name, area) values (12, 'Dibbert Inc', 'Sales');
insert into Company (idCompany, name, area) values (13, 'Smitham, Beatty and Nader', 'Human Resources');
insert into Company (idCompany, name, area) values (14, 'Balistreri, Johnston and Farrell', 'Training');
insert into Company (idCompany, name, area) values (15, 'Yundt Group', 'Engineering');
insert into Company (idCompany, name, area) values (16, 'Goyette, Rowe and Abshire', 'Engineering');
insert into Company (idCompany, name, area) values (17, 'Rutherford and Sons', 'Support');
insert into Company (idCompany, name, area) values (18, 'Weber-Cronin', 'Services');
insert into Company (idCompany, name, area) values (19, 'Kub, Gutmann and Leannon', 'Accounting');
insert into Company (idCompany, name, area) values (20, 'Hayes LLC', 'Accounting');
insert into Company (idCompany, name, area) values (21, 'Kshlerin LLC', 'Support');
insert into Company (idCompany, name, area) values (22, 'Prohaska-Hagenes', 'Business Development');
insert into Company (idCompany, name, area) values (23, 'Fisher-Littel', 'Legal');
insert into Company (idCompany, name, area) values (24, 'Mayert Inc', 'Accounting');
insert into Company (idCompany, name, area) values (25, 'Lueilwitz LLC', 'Training');
insert into Company (idCompany, name, area) values (26, 'Bosco, Koch and Kunze', 'Product Management');
insert into Company (idCompany, name, area) values (27, 'Marks-Hilll', 'Legal');
insert into Company (idCompany, name, area) values (28, 'Shanahan-Klein', 'Support');
insert into Company (idCompany, name, area) values (29, 'Graham-Hills', 'Business Development');
insert into Company (idCompany, name, area) values (30, 'Kirlin, Wolf and Pfannerstill', 'Sales');
insert into Company (idCompany, name, area) values (31, 'Gerhold, Schumm and Smitham', 'Training');
insert into Company (idCompany, name, area) values (32, 'Olson-Becker', 'Accounting');
insert into Company (idCompany, name, area) values (33, 'Kshlerin-Watsica', 'Product Management');
insert into Company (idCompany, name, area) values (34, 'White LLC', 'Training');
insert into Company (idCompany, name, area) values (35, 'Stiedemann-Carroll', 'Training');
insert into Company (idCompany, name, area) values (36, 'Mitchell Group', 'Human Resources');
insert into Company (idCompany, name, area) values (37, 'Orn, Hammes and Lemke', 'Services');
insert into Company (idCompany, name, area) values (38, 'Hammes Group', 'Engineering');
insert into Company (idCompany, name, area) values (39, 'Boyle Inc', 'Research and Development');
insert into Company (idCompany, name, area) values (40, 'Wehner-Goodwin', 'Business Development');
insert into Company (idCompany, name, area) values (41, 'Renner, Renner and Nikolaus', 'Research and Development');
insert into Company (idCompany, name, area) values (42, 'Mills Group', 'Legal');
insert into Company (idCompany, name, area) values (43, 'Rodriguez, Swaniawski and Veum', 'Product Management');
insert into Company (idCompany, name, area) values (44, 'Green-O''Kon', 'Product Management');
insert into Company (idCompany, name, area) values (45, 'McCullough and Sons', 'Accounting');
insert into Company (idCompany, name, area) values (46, 'Vandervort-Hammes', 'Services');
insert into Company (idCompany, name, area) values (47, 'Cassin Inc', 'Business Development');
insert into Company (idCompany, name, area) values (48, 'Kilback and Sons', 'Support');
insert into Company (idCompany, name, area) values (49, 'Heidenreich, Bashirian and Gusikowski', 'Marketing');
insert into Company (idCompany, name, area) values (50, 'Haley, Gutkowski and Nolan', 'Product Management');
insert into Company (idCompany, name, area) values (51, 'Buckridge, Halvorson and Gibson', 'Research and Development');
insert into Company (idCompany, name, area) values (52, 'Kris Inc', 'Business Development');
insert into Company (idCompany, name, area) values (53, 'Greenholt, Greenholt and Romaguera', 'Research and Development');
insert into Company (idCompany, name, area) values (54, 'Lakin, Ledner and Wisoky', 'Accounting');
insert into Company (idCompany, name, area) values (55, 'Pagac LLC', 'Services');
insert into Company (idCompany, name, area) values (56, 'Hessel, Rogahn and Crooks', 'Marketing');
insert into Company (idCompany, name, area) values (57, 'Dach-Keebler', 'Training');
insert into Company (idCompany, name, area) values (58, 'Gleason-Gusikowski', 'Legal');
insert into Company (idCompany, name, area) values (59, 'Lesch-Wehner', 'Product Management');
insert into Company (idCompany, name, area) values (60, 'Koss-Mueller', 'Engineering');
insert into Company (idCompany, name, area) values (61, 'Metz-Carter', 'Accounting');
insert into Company (idCompany, name, area) values (62, 'Sipes, Becker and Powlowski', 'Product Management');
insert into Company (idCompany, name, area) values (63, 'Ziemann Inc', 'Engineering');
insert into Company (idCompany, name, area) values (64, 'Lehner Group', 'Support');
insert into Company (idCompany, name, area) values (65, 'Luettgen, Ledner and Streich', 'Marketing');
insert into Company (idCompany, name, area) values (66, 'Haley, Keeling and Koelpin', 'Research and Development');
insert into Company (idCompany, name, area) values (67, 'VonRueden-Kertzmann', 'Support');
insert into Company (idCompany, name, area) values (68, 'Dare Group', 'Marketing');
insert into Company (idCompany, name, area) values (69, 'Oberbrunner and Sons', 'Human Resources');
insert into Company (idCompany, name, area) values (70, 'Ward, Greenfelder and Grimes', 'Services');
insert into Company (idCompany, name, area) values (71, 'Dickens, Lesch and Hauck', 'Support');
insert into Company (idCompany, name, area) values (72, 'Kirlin-Kuhlman', 'Product Management');
insert into Company (idCompany, name, area) values (73, 'Hilpert, Zulauf and Nitzsche', 'Sales');
insert into Company (idCompany, name, area) values (74, 'Connelly and Sons', 'Accounting');
insert into Company (idCompany, name, area) values (75, 'Stamm Inc', 'Human Resources');
insert into Company (idCompany, name, area) values (76, 'Bechtelar Inc', 'Engineering');
insert into Company (idCompany, name, area) values (77, 'McDermott-Gusikowski', 'Human Resources');
insert into Company (idCompany, name, area) values (78, 'Lind, Aufderhar and Hettinger', 'Marketing');
insert into Company (idCompany, name, area) values (79, 'Ondricka, Bruen and Blick', 'Research and Development');
insert into Company (idCompany, name, area) values (80, 'Lakin-Zemlak', 'Legal');
insert into Company (idCompany, name, area) values (81, 'Nader, Effertz and Hammes', 'Research and Development');
insert into Company (idCompany, name, area) values (82, 'Wiegand-Cartwright', 'Engineering');
insert into Company (idCompany, name, area) values (83, 'Nicolas Inc', 'Legal');
insert into Company (idCompany, name, area) values (84, 'Hackett, Sauer and Weimann', 'Human Resources');
insert into Company (idCompany, name, area) values (85, 'Lesch-Ryan', 'Services');
insert into Company (idCompany, name, area) values (86, 'Russel LLC', 'Human Resources');
insert into Company (idCompany, name, area) values (87, 'Greenholt and Sons', 'Services');
insert into Company (idCompany, name, area) values (88, 'Marquardt Inc', 'Research and Development');
insert into Company (idCompany, name, area) values (89, 'Lubowitz-Grant', 'Business Development');
insert into Company (idCompany, name, area) values (90, 'Will-Dickinson', 'Accounting');
insert into Company (idCompany, name, area) values (91, 'Wilderman, Huels and Rutherford', 'Research and Development');
insert into Company (idCompany, name, area) values (92, 'Kuhn Group', 'Sales');
insert into Company (idCompany, name, area) values (93, 'Gusikowski Group', 'Services');
insert into Company (idCompany, name, area) values (94, 'Schaefer LLC', 'Business Development');
insert into Company (idCompany, name, area) values (95, 'Keebler, Price and McCullough', 'Training');
insert into Company (idCompany, name, area) values (96, 'Jacobi, Emard and Stamm', 'Accounting');
insert into Company (idCompany, name, area) values (97, 'Sawayn-Lakin', 'Human Resources');
insert into Company (idCompany, name, area) values (98, 'Boyer-Haley', 'Legal');
insert into Company (idCompany, name, area) values (99, 'Mraz, Harber and West', 'Services');
insert into Company (idCompany, name, area) values (100, 'Hessel Group', 'Engineering');
