insert into University (idUniversity, university_name, campus_name, country) values (1, 'Kabul Medical University', 'Qaram Qōl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (2, 'National Military Academy of Afghanistan', 'Farah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (3, 'Kateb Institute of Higher Education', 'Sangar Sarāy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (4, 'Ibn Sina University', 'Khāsh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (5, 'Kabul Medical University', 'Rustāq', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (6, 'National Military Academy of Afghanistan', 'Barg-e Matāl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (7, 'Takhar University', 'Amānzī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (8, 'Khurasan University', 'Uruzgān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (9, 'Sadat Institute of Higher Education', 'Zīrakī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (10, 'Parwan University', 'Qal‘ah-ye Kuhnah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (11, 'Pamir University', 'Kandahār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (12, 'Bamiyan University', 'Andkhōy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (13, 'Khurasan University', 'Pachīr wa Āgām', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (14, 'Karwan Institute of Higher Education', 'Bal Chirāgh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (15, 'Takhar University', 'Āsmār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (16, 'Kabul Health Sciences Institute', 'Maymana', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (17, 'Rana Institute of Higher Education', 'Manogay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (18, 'Pamir University', 'Mīr Bachah Kōṯ', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (19, 'Kardan University', '’Unābah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (20, 'Salam University', 'Lashkar Gāh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (21, 'Bamiyan University', 'Dehī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (22, 'Dunya Institute of Higher Education', 'Āqchah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (23, 'Aria Institute of Higher Education', '’Unābah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (24, 'Dawat University', 'Cool űrhajó', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (25, 'Takhar University', 'Cool űrhajó', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (26, 'Maryam Institute of Higher Education', 'Khulm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (27, 'Paktia University', 'Kalān Deh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (28, 'Kardan University', 'Zīrakī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (29, 'Herat University', '‘Alāqahdārī Gēlān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (30, 'Nangarhar University', 'Mutā Khān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (31, 'Aria Institute of Higher Education', 'Nāṟay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (32, 'Dawat University', 'Mazār-e Sharīf', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (33, 'Rana Institute of Higher Education', 'Gardēz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (34, 'Parwan University', 'Salām Khēl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (35, 'Pamir University', 'Nahrīn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (36, 'Parwan University', 'Rabāţ-e Sangī-ye Pā’īn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (37, 'Kardan University', 'Shibirghān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (38, 'Bost University', 'Kabul', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (39, 'Al-Birony University', 'Qarah Bāgh Bāzār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (40, 'Takhar University', 'Zaranj', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (41, 'Bost University', 'Taloqan', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (42, 'Kaboora Institute of Higher Education', 'Pul-e Sangī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (43, 'Bamiyan University', 'Nūsay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (44, 'Bamiyan University', 'Aībak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (45, 'Khurasan University', 'Imām Şāḩib', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (46, 'Badakhshan University', 'Dūāb', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (47, 'Kabul University', 'Jawand', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (48, 'Sadat Institute of Higher Education', 'Andkhōy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (49, 'Kabul Education University', 'Quchanghī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (50, 'National Military Academy of Afghanistan', 'Kafir Qala', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (51, 'Aria Institute of Higher Education', 'Kabul', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (52, 'Takhar University', 'Qaram Qōl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (53, 'Dawat University', 'Aībak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (54, 'Jawzjan University', 'Qarah Bāgh Bāzār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (55, 'Al-Birony University', 'Taloqan', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (56, 'American University of Afghanistan', 'Dowlatyār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (57, 'Rana Institute of Higher Education', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (58, 'Kabul University', 'Āsmār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (59, 'Bakhtar University', 'Nīkêh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (60, 'Ghazni University', 'Markaz-e Ḩukūmat-e Darwēshān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (61, 'Bakhtar University', 'Ashkāsham', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (62, 'American University of Afghanistan', 'Nayak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (63, 'Kabul University', 'Tsapêraī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (64, 'Karwan Institute of Higher Education', 'Mardīān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (65, 'Ibn Sina University', 'Dehī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (66, 'Herat University', 'Deh-e Now', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (67, 'American University of Afghanistan', 'Shahrak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (68, 'American University of Afghanistan', 'Kunduz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (69, 'Kandahar University', 'Gardēz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (70, 'Badakhshan University', 'Now Zād', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (71, 'Nangarhar University', 'Qarchī Gak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (72, 'American University of Afghanistan', 'Imām Şāḩib', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (73, 'Bost University', 'Balkh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (74, 'Nangarhar University', 'Tsowkêy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (75, 'Aria Institute of Higher Education', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (76, 'Khurasan University', 'Farah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (77, 'Al-Birony University', 'Babasakhib', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (78, 'Bost University', 'Ḩukūmat-e Shīnkaī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (79, 'Kabul University', 'Baghlān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (80, 'Faryab Higher Education Institute', 'Tsowkêy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (81, 'Parwan University', 'Khūgyāṉī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (82, 'Rana Institute of Higher Education', 'Paghmān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (83, 'Balkh University', 'Ḩukūmat-e Shīnkaī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (84, 'Dunya Institute of Higher Education', 'Dū Laīnah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (85, 'Herat University', 'Khulm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (86, 'Bakhtar University', 'Imām Şāḩib', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (87, 'Rana Institute of Higher Education', 'Quchanghī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (88, 'Afghan University', 'Dasht-e Archī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (89, 'Dawat University', 'Karukh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (90, 'Jawzjan University', 'Chahār Burj', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (91, 'Aria Institute of Higher Education', 'Āsmār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (92, 'Sadat Institute of Higher Education', 'Bāmyān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (93, 'Kandahar University', 'Shahrak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (94, 'Rana Institute of Higher Education', 'Injīl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (95, 'Rana Institute of Higher Education', 'Cool űrhajó', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (96, 'Herat University', 'Surkh Bilandī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (97, 'Al-Birony University', 'Bal Chirāgh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (98, 'Kabul University', 'Khāsh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (99, 'Kabul Medical University', 'Mutā Khān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (100, 'Taj Institute of Higher Education', 'Shahrak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (101, 'Faryab Higher Education Institute', 'Qal‘ah-ye Kuhnah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (102, 'Khana-e-Noor Institute of Higher Education', 'Anār Darah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (103, 'Maryam Institute of Higher Education', 'Imām Şāḩib', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (104, 'Khurasan University', 'Adraskan', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (105, 'Aria Institute of Higher Education', 'Qal‘ah-ye Shahr', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (106, 'Khurasan University', 'Mutā Khān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (107, 'Bost University', 'Dowlatyār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (108, 'Taj Institute of Higher Education', 'Pachīr wa Āgām', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (109, 'Dunya Institute of Higher Education', 'Wuṯahpūr', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (110, 'Afghan University', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (111, 'Baghlan University', 'Charikar', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (112, 'Bamiyan University', 'Khōshāmand', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (113, 'Salam University', 'Nayak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (114, 'Herat University', 'Rabāţ-e Sangī-ye Pā’īn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (115, 'Dunya Institute of Higher Education', 'Sangar Sarāy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (116, 'Khurasan University', 'Shahrak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (117, 'Faryab Higher Education Institute', 'Āqchah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (118, 'Bamiyan University', 'Khinjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (119, 'Dunya Institute of Higher Education', 'Shibirghān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (120, 'Salam University', 'Andkhōy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (121, 'Taj Institute of Higher Education', 'Khinjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (122, 'Kabul Health Sciences Institute', 'Qal‘ah-ye Shahr', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (123, 'Karwan Institute of Higher Education', 'Khinjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (124, 'Kabul Medical University', 'Khōst', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (125, 'American University of Afghanistan', 'Balkh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (126, 'Khurasan University', 'Mandōl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (127, 'Paktia University', 'Kafir Qala', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (128, 'Maryam Institute of Higher Education', 'Chisht-e Sharīf', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (129, 'Dunya Institute of Higher Education', 'Dūāb', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (130, 'Badakhshan University', 'Rustāq', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (131, 'Maryam Institute of Higher Education', 'Māymay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (132, 'Taj Institute of Higher Education', 'Markaz-e Woluswalī-ye Āchīn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (133, 'Jawzjan University', 'Dowlatyār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (134, 'Sadat Institute of Higher Education', 'Nayak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (135, 'Maryam Institute of Higher Education', 'Bagrāmī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (136, 'Afghan University', 'Pārūn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (137, 'Afghan University', 'Rustāq', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (138, 'Herat University', 'Khōst', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (139, 'Faryab Higher Education Institute', 'Ārt Khwājah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (140, 'Kardan University', 'Qala i Naw', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (141, 'Parwan University', 'Taloqan', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (142, 'Takhar University', 'Fayzabad', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (143, 'Shaikh Zayed University', 'Khulm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (144, 'Baghlan University', 'Ghormach', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (145, 'Taj Institute of Higher Education', 'Khōshāmand', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (146, 'Dunya Institute of Higher Education', 'Farah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (147, 'Dunya Institute of Higher Education', 'Fayzabad', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (148, 'Kabul Education University', 'Kafir Qala', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (149, 'Pamir University', 'Shīnḏanḏ', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (150, 'Ibn Sina University', 'Maymana', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (151, 'Jawzjan University', 'Qarchī Gak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (152, 'Maryam Institute of Higher Education', 'Rū-ye Sang', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (153, 'American University of Afghanistan', 'Ghormach', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (154, 'Kabul Health Sciences Institute', 'Ārt Khwājah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (155, 'Faryab Higher Education Institute', 'Shibirghān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (156, 'Rana Institute of Higher Education', 'Shīnḏanḏ', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (157, 'Aria Institute of Higher Education', 'Anār Darah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (158, 'Kaboora Institute of Higher Education', 'Manogay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (159, 'Salam University', 'Gardēz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (160, 'Afghan University', 'Nayak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (161, 'Baghlan University', 'Māymay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (162, 'National Military Academy of Afghanistan', '’Unābah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (163, 'Kardan University', 'Paghmān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (164, 'Dawat University', 'Pul-e Sangī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (165, 'Kabul University', 'Khudāydād Khēl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (166, 'Salam University', 'Mīr Bachah Kōṯ', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (167, 'Bakhtar University', 'Chakaray', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (168, 'Ibn Sina University', 'Pul-e Sangī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (169, 'Jawzjan University', 'Balkh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (170, 'National Military Academy of Afghanistan', 'Zīrakī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (171, 'Nangarhar University', 'Panjāb', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (172, 'Dunya Institute of Higher Education', 'Khānaqāh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (173, 'Dunya Institute of Higher Education', 'Quchanghī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (174, 'Bost University', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (175, 'Kabul Health Sciences Institute', 'Rustāq', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (176, 'Rana Institute of Higher Education', 'Gereshk', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (177, 'Kabul Education University', 'Khōshāmand', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (178, 'Herat University', 'Mehtar Lām', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (179, 'Al-Birony University', 'Pāshmūl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (180, 'Bakhtar University', '‘Alāqahdārī Kirān wa Munjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (181, 'Badakhshan University', 'Rustāq', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (182, 'Pamir University', 'Kalān Deh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (183, 'Herat University', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (184, 'Dawat University', 'Ḩāfiz̧ Moghul', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (185, 'Ghazni University', 'Cool űrhajó', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (186, 'Paktia University', 'Karukh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (187, 'Khurasan University', 'Shibirghān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (188, 'Khana-e-Noor Institute of Higher Education', 'Fayzabad', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (189, 'Sadat Institute of Higher Education', 'Dū Laīnah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (190, 'Nangarhar University', 'Andkhōy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (191, 'Karwan Institute of Higher Education', 'Nahrīn', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (192, 'American University of Afghanistan', 'Kunduz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (193, 'Salam University', 'Maymana', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (194, 'Salam University', 'Barg-e Matāl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (195, 'Badakhshan University', 'Dowr-e Rabāţ', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (196, 'Faryab Higher Education Institute', 'Chimtāl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (197, 'Salam University', 'Khāsh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (198, 'Dawat University', 'Farah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (199, 'Aria Institute of Higher Education', 'Pul-e Khumrī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (200, 'Dawat University', 'Cool űrhajó', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (201, 'Dunya Institute of Higher Education', 'Āsmār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (202, 'Ibn Sina University', 'Būrkah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (203, 'Ghazni University', 'Sang-e Chārak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (204, 'Kardan University', 'Kushk', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (205, 'Nangarhar University', 'Khafizan', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (206, 'Ghazni University', 'Wuṯahpūr', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (207, 'Ghazni University', 'Khanabad', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (208, 'Maryam Institute of Higher Education', 'Balkh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (209, 'Afghan University', 'Khānaqāh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (210, 'Kardan University', 'Chisht-e Sharīf', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (211, 'Dawat University', '‘Alāqahdārī Gēlān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (212, 'Pamir University', 'Rū-ye Sang', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (213, 'Faryab Higher Education Institute', 'Ḩukūmat-e Shīnkaī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (214, 'Bamiyan University', 'Shahr-e Şafā', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (215, 'Afghan University', 'Chowṉêy', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (216, 'Kandahar University', 'Qala i Naw', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (217, 'Al-Birony University', 'Qal‘ah-ye Shahr', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (218, 'Dawat University', 'Qal‘ah-ye Fārsī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (219, 'Sadat Institute of Higher Education', '‘Alāqahdārī Kirān wa Munjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (220, 'Kabul Medical University', 'Gardēz', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (221, 'Polytechnical University of Kabul', 'Muḩammad Āghah Wuluswālī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (222, 'Khana-e-Noor Institute of Higher Education', 'Māymay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (223, 'Taj Institute of Higher Education', 'Khānaqāh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (224, 'Rana Institute of Higher Education', '‘Alāqahdārī Kirān wa Munjān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (225, 'Kaboora Institute of Higher Education', 'Maymana', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (226, 'Afghan University', 'Dasht-e Qal‘ah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (227, 'Takhar University', '‘Alāqahdārī Gēlān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (228, 'Bost University', 'Uruzgān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (229, 'Takhar University', 'Zīrakī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (230, 'Afghan University', 'Jawand', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (231, 'Karwan Institute of Higher Education', 'Faīẕābād', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (232, 'Kabul University', 'Shahrak', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (233, 'Pamir University', 'Nīkêh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (234, 'Paktia University', 'Nīkêh', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (235, 'Balkh University', 'Ashkāsham', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (236, 'Dunya Institute of Higher Education', 'Pas Pul', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (237, 'Taj Institute of Higher Education', 'Surkh Bilandī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (238, 'Dunya Institute of Higher Education', 'Manogay', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (239, 'Takhar University', 'Uruzgān', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (240, 'Kandahar University', 'Jurm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (241, 'Parwan University', 'Chimtāl', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (242, 'Kandahar University', 'Khulm', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (243, 'Taj Institute of Higher Education', 'Khanabad', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (244, 'Kabul University', 'Dū Qal‘ah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (245, 'Ibn Sina University', 'Charikar', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (246, 'Kaboora Institute of Higher Education', 'Kishk-e Nakhūd', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (247, 'Bakhtar University', 'Kandahār', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (248, 'Karwan Institute of Higher Education', 'Ārt Khwājah', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (249, 'Balkh University', 'Qal‘ah-ye Fārsī', 'Afghanistan');
insert into University (idUniversity, university_name, campus_name, country) values (250, 'Badakhshan University', 'Wuṯahpūr', 'Afghanistan');
