insert into Faculty (idFaculty, faculty_name, idUniversity) values (1, 'Graphic Design', 154);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (2, 'English Literature', 3);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (3, 'Psychology', 153);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (4, 'Sports Science', 124);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (5, 'Biomedical Engineering', 23);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (6, 'Biology', 109);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (7, 'Civil Engineering', 46);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (8, 'English Literature', 175);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (9, 'History', 141);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (10, 'Economics', 24);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (11, 'Biomedical Engineering', 175);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (12, 'Film Studies', 75);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (13, 'Drama', 150);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (14, 'Human Resources', 17);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (15, 'Human Resources', 61);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (16, 'Geology', 19);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (17, 'Fine Arts', 100);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (18, 'Forensic Science', 159);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (19, 'Agricultural Science', 226);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (20, 'Geography', 176);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (21, 'Religious Studies', 230);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (22, 'Computer Science', 227);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (23, 'Criminal Justice', 192);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (24, 'Public Health', 161);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (25, 'Nursing', 176);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (26, 'Drama', 238);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (27, 'Foreign Languages', 84);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (28, 'Film Studies', 86);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (29, 'Urban Planning', 15);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (30, 'Political Science', 220);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (31, 'Biology', 230);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (32, 'Counseling', 149);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (33, 'Business Administration', 4);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (34, 'Creative Writing', 23);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (35, 'Public Health', 161);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (36, 'Business Administration', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (37, 'English Literature', 158);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (38, 'Veterinary Science', 87);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (39, 'Criminal Justice', 134);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (40, 'Environmental Science', 212);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (41, 'Electrical Engineering', 223);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (42, 'Geography', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (43, 'Forensic Science', 119);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (44, 'Political Science', 2);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (45, 'Electrical Engineering', 91);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (46, 'Physics', 212);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (47, 'Political Science', 178);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (48, 'Business Administration', 245);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (49, 'Geology', 103);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (50, 'Architecture', 196);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (51, 'Graphic Design', 178);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (52, 'Forensic Science', 208);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (53, 'Fine Arts', 181);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (54, 'History', 196);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (55, 'Physics', 112);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (56, 'Creative Writing', 75);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (57, 'Biology', 76);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (58, 'Fine Arts', 130);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (59, 'English Literature', 162);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (60, 'Film Studies', 215);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (61, 'Chemistry', 114);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (62, 'Computer Science', 55);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (63, 'Political Science', 240);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (64, 'Marketing', 211);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (65, 'Mathematics', 224);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (66, 'Economics', 203);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (67, 'Industrial Design', 53);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (68, 'Criminal Justice', 244);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (69, 'Human Resources', 233);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (70, 'Forensic Science', 33);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (71, 'Drama', 26);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (72, 'Political Science', 191);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (73, 'Industrial Design', 7);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (74, 'Film Studies', 11);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (75, 'Urban Planning', 42);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (76, 'Computer Science', 50);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (77, 'Chemistry', 107);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (78, 'Creative Writing', 250);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (79, 'Graphic Design', 182);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (80, 'Religious Studies', 85);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (81, 'Agricultural Science', 3);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (82, 'Geography', 188);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (83, 'Sociology', 128);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (84, 'History', 125);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (85, 'Religious Studies', 93);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (86, 'Agricultural Science', 128);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (87, 'Religious Studies', 229);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (88, 'Linguistics', 99);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (89, 'Mechanical Engineering', 216);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (90, 'Computer Science', 234);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (91, 'Religious Studies', 19);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (92, 'Communications', 29);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (93, 'Geography', 146);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (94, 'Foreign Languages', 71);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (95, 'Foreign Languages', 32);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (96, 'Education', 103);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (97, 'Public Health', 136);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (98, 'Biomedical Engineering', 20);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (99, 'English Literature', 140);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (100, 'Sociology', 238);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (101, 'Economics', 243);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (102, 'Geography', 136);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (103, 'Graphic Design', 141);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (104, 'Criminal Justice', 152);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (105, 'Social Work', 140);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (106, 'Nutrition', 217);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (107, 'Kinesiology', 111);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (108, 'Economics', 167);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (109, 'Mathematics', 152);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (110, 'Graphic Design', 245);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (111, 'Kinesiology', 240);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (112, 'Sociology', 23);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (113, 'Architecture', 60);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (114, 'Biomedical Engineering', 245);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (115, 'Psychology', 17);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (116, 'Nursing', 15);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (117, 'Economics', 204);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (118, 'Nursing', 239);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (119, 'Urban Planning', 174);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (120, 'Communications', 50);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (121, 'Philosophy', 123);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (122, 'Film Studies', 203);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (123, 'Religious Studies', 28);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (124, 'Linguistics', 105);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (125, 'Computer Science', 218);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (126, 'Fine Arts', 83);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (127, 'Philosophy', 74);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (128, 'Mathematics', 14);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (129, 'Counseling', 149);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (130, 'Cultural Studies', 158);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (131, 'Creative Writing', 43);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (132, 'Foreign Languages', 95);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (133, 'Creative Writing', 29);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (134, 'Electrical Engineering', 210);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (135, 'Geography', 96);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (136, 'Political Science', 66);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (137, 'Criminal Justice', 27);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (138, 'Electrical Engineering', 59);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (139, 'Foreign Languages', 64);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (140, 'Biomedical Engineering', 178);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (141, 'Sports Science', 178);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (142, 'Criminal Justice', 47);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (143, 'Architecture', 39);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (144, 'Criminal Justice', 44);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (145, 'Linguistics', 237);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (146, 'Creative Writing', 160);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (147, 'Film Studies', 136);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (148, 'Kinesiology', 94);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (149, 'Materials Science', 83);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (150, 'Foreign Languages', 56);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (151, 'Urban Planning', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (152, 'Communications', 218);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (153, 'Anthropology', 115);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (154, 'Biomedical Engineering', 137);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (155, 'Materials Science', 11);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (156, 'Kinesiology', 147);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (157, 'Education', 249);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (158, 'History', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (159, 'Agricultural Science', 29);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (160, 'Nursing', 53);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (161, 'Agricultural Science', 48);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (162, 'History', 11);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (163, 'Public Health', 184);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (164, 'Psychology', 85);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (165, 'Nutrition', 35);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (166, 'Creative Writing', 98);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (167, 'Agricultural Science', 8);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (168, 'Agricultural Science', 51);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (169, 'Civil Engineering', 44);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (170, 'Architecture', 12);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (171, 'Political Science', 225);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (172, 'Human Resources', 201);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (173, 'Music', 65);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (174, 'Anthropology', 59);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (175, 'Industrial Design', 62);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (176, 'History', 181);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (177, 'Political Science', 151);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (178, 'Cultural Studies', 98);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (179, 'Civil Engineering', 134);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (180, 'Sports Science', 170);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (181, 'Foreign Languages', 154);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (182, 'Mechanical Engineering', 83);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (183, 'Sociology', 219);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (184, 'Communications', 20);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (185, 'Sports Science', 169);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (186, 'History', 153);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (187, 'Sociology', 120);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (188, 'Public Health', 49);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (189, 'Nutrition', 141);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (190, 'Veterinary Science', 102);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (191, 'Marketing', 171);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (192, 'Music', 39);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (193, 'Mechanical Engineering', 145);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (194, 'Film Studies', 97);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (195, 'Political Science', 70);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (196, 'Urban Planning', 71);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (197, 'Foreign Languages', 78);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (198, 'Music', 51);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (199, 'Veterinary Science', 14);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (200, 'Philosophy', 80);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (201, 'Veterinary Science', 55);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (202, 'Urban Planning', 194);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (203, 'Music', 231);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (204, 'Counseling', 43);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (205, 'Foreign Languages', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (206, 'Nutrition', 40);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (207, 'Civil Engineering', 213);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (208, 'Religious Studies', 234);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (209, 'Nutrition', 217);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (210, 'Communications', 205);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (211, 'Urban Planning', 15);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (212, 'Biomedical Engineering', 208);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (213, 'Civil Engineering', 135);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (214, 'Computer Science', 247);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (215, 'Sports Science', 186);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (216, 'Psychology', 212);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (217, 'Fine Arts', 48);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (218, 'Biomedical Engineering', 33);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (219, 'English Literature', 207);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (220, 'History', 187);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (221, 'Materials Science', 116);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (222, 'Sociology', 62);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (223, 'Social Work', 191);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (224, 'Graphic Design', 18);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (225, 'Human Resources', 217);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (226, 'Physics', 7);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (227, 'Film Studies', 103);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (228, 'Religious Studies', 48);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (229, 'Materials Science', 38);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (230, 'Drama', 75);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (231, 'English Literature', 102);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (232, 'Economics', 195);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (233, 'Public Health', 56);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (234, 'Civil Engineering', 43);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (235, 'History', 167);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (236, 'Kinesiology', 165);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (237, 'Materials Science', 77);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (238, 'History', 68);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (239, 'Nursing', 247);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (240, 'Communications', 184);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (241, 'Film Studies', 84);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (242, 'Kinesiology', 149);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (243, 'Film Studies', 46);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (244, 'Human Resources', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (245, 'Cultural Studies', 191);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (246, 'Anthropology', 94);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (247, 'Education', 118);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (248, 'Industrial Design', 167);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (249, 'Architecture', 34);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (250, 'Architecture', 38);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (251, 'Geology', 73);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (252, 'History', 236);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (253, 'Creative Writing', 224);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (254, 'Graphic Design', 206);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (255, 'Nursing', 63);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (256, 'Veterinary Science', 170);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (257, 'Foreign Languages', 85);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (258, 'Communications', 45);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (259, 'Psychology', 14);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (260, 'Cultural Studies', 230);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (261, 'Education', 66);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (262, 'Sports Science', 207);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (263, 'Political Science', 226);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (264, 'Music', 87);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (265, 'Social Work', 194);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (266, 'Communications', 231);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (267, 'Communications', 12);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (268, 'Nursing', 94);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (269, 'Geology', 29);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (270, 'Biomedical Engineering', 157);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (271, 'Computer Science', 132);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (272, 'Agricultural Science', 59);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (273, 'English Literature', 73);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (274, 'Physics', 80);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (275, 'Agricultural Science', 91);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (276, 'Geography', 39);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (277, 'Biomedical Engineering', 165);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (278, 'Economics', 145);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (279, 'Drama', 192);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (280, 'Business Administration', 140);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (281, 'Drama', 243);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (282, 'Sociology', 109);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (283, 'Veterinary Science', 225);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (284, 'Anthropology', 86);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (285, 'Kinesiology', 97);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (286, 'Environmental Science', 126);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (287, 'Human Resources', 246);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (288, 'Biology', 104);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (289, 'Environmental Science', 247);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (290, 'Architecture', 103);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (291, 'Geology', 82);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (292, 'Drama', 91);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (293, 'Environmental Science', 242);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (294, 'Economics', 176);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (295, 'Architecture', 235);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (296, 'Graphic Design', 96);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (297, 'Nursing', 166);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (298, 'Sociology', 37);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (299, 'Biology', 154);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (300, 'Mathematics', 84);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (301, 'Graphic Design', 175);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (302, 'Cultural Studies', 234);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (303, 'Nursing', 9);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (304, 'Foreign Languages', 244);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (305, 'History', 126);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (306, 'Geology', 18);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (307, 'History', 209);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (308, 'Public Health', 116);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (309, 'Sports Science', 114);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (310, 'Education', 18);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (311, 'Electrical Engineering', 174);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (312, 'Architecture', 196);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (313, 'Creative Writing', 25);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (314, 'Sociology', 167);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (315, 'Education', 63);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (316, 'Cultural Studies', 130);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (317, 'Anthropology', 75);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (318, 'Materials Science', 20);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (319, 'Marketing', 220);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (320, 'Music', 67);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (321, 'Philosophy', 162);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (322, 'Nursing', 47);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (323, 'Biomedical Engineering', 123);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (324, 'History', 210);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (325, 'Film Studies', 152);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (326, 'Electrical Engineering', 58);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (327, 'Sociology', 191);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (328, 'Foreign Languages', 2);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (329, 'Linguistics', 198);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (330, 'Business Administration', 78);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (331, 'Counseling', 163);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (332, 'Biomedical Engineering', 102);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (333, 'Physics', 179);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (334, 'English Literature', 73);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (335, 'Religious Studies', 68);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (336, 'English Literature', 31);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (337, 'Film Studies', 233);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (338, 'Geology', 3);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (339, 'Materials Science', 112);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (340, 'Psychology', 117);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (341, 'Creative Writing', 75);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (342, 'Education', 123);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (343, 'Computer Science', 4);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (344, 'Urban Planning', 81);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (345, 'Veterinary Science', 63);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (346, 'Business Administration', 238);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (347, 'Linguistics', 7);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (348, 'Film Studies', 71);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (349, 'Psychology', 113);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (350, 'Film Studies', 159);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (351, 'Drama', 36);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (352, 'Physics', 159);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (353, 'Anthropology', 80);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (354, 'Veterinary Science', 171);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (355, 'Psychology', 210);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (356, 'Graphic Design', 210);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (357, 'Political Science', 157);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (358, 'Social Work', 66);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (359, 'Geography', 140);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (360, 'Business Administration', 103);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (361, 'Electrical Engineering', 122);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (362, 'Computer Science', 248);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (363, 'Business Administration', 113);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (364, 'Forensic Science', 46);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (365, 'Physics', 173);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (366, 'Business Administration', 14);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (367, 'Nutrition', 155);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (368, 'Graphic Design', 3);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (369, 'Biomedical Engineering', 111);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (370, 'Environmental Science', 137);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (371, 'Industrial Design', 185);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (372, 'Counseling', 29);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (373, 'English Literature', 97);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (374, 'Nursing', 163);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (375, 'Electrical Engineering', 62);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (376, 'Political Science', 127);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (377, 'Foreign Languages', 166);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (378, 'Marketing', 225);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (379, 'Drama', 100);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (380, 'Economics', 219);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (381, 'Graphic Design', 114);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (382, 'Sports Science', 222);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (383, 'Business Administration', 186);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (384, 'Linguistics', 61);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (385, 'Fine Arts', 49);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (386, 'Cultural Studies', 151);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (387, 'Mechanical Engineering', 128);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (388, 'Urban Planning', 249);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (389, 'Religious Studies', 115);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (390, 'Political Science', 89);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (391, 'Criminal Justice', 128);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (392, 'Philosophy', 148);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (393, 'Geography', 233);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (394, 'Forensic Science', 80);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (395, 'Communications', 206);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (396, 'Public Health', 220);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (397, 'English Literature', 89);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (398, 'Veterinary Science', 83);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (399, 'Civil Engineering', 208);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (400, 'Education', 88);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (401, 'Criminal Justice', 90);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (402, 'Sociology', 79);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (403, 'Linguistics', 15);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (404, 'Linguistics', 189);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (405, 'Nutrition', 219);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (406, 'Sports Science', 91);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (407, 'History', 230);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (408, 'Criminal Justice', 161);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (409, 'Criminal Justice', 183);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (410, 'Materials Science', 122);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (411, 'English Literature', 24);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (412, 'Sports Science', 48);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (413, 'Economics', 7);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (414, 'History', 247);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (415, 'Anthropology', 148);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (416, 'Marketing', 181);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (417, 'Geography', 147);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (418, 'Religious Studies', 76);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (419, 'Biomedical Engineering', 146);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (420, 'Music', 213);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (421, 'Sociology', 139);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (422, 'Philosophy', 14);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (423, 'Fine Arts', 95);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (424, 'Philosophy', 101);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (425, 'Materials Science', 17);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (426, 'Materials Science', 65);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (427, 'Marketing', 49);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (428, 'Fine Arts', 163);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (429, 'Nursing', 7);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (430, 'Nursing', 110);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (431, 'Forensic Science', 107);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (432, 'Religious Studies', 85);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (433, 'Biomedical Engineering', 130);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (434, 'Physics', 106);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (435, 'Chemistry', 229);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (436, 'Education', 55);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (437, 'Industrial Design', 240);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (438, 'Electrical Engineering', 72);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (439, 'Urban Planning', 192);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (440, 'Geography', 99);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (441, 'Electrical Engineering', 96);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (442, 'Psychology', 94);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (443, 'Criminal Justice', 181);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (444, 'English Literature', 178);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (445, 'Electrical Engineering', 11);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (446, 'Materials Science', 138);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (447, 'Foreign Languages', 48);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (448, 'History', 212);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (449, 'Mathematics', 133);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (450, 'Nursing', 53);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (451, 'Social Work', 228);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (452, 'Mechanical Engineering', 201);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (453, 'Mechanical Engineering', 232);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (454, 'Fine Arts', 71);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (455, 'Mechanical Engineering', 43);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (456, 'Chemistry', 90);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (457, 'Foreign Languages', 211);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (458, 'Graphic Design', 111);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (459, 'Philosophy', 138);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (460, 'Creative Writing', 49);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (461, 'Chemistry', 63);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (462, 'Nutrition', 94);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (463, 'Sports Science', 80);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (464, 'Computer Science', 1);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (465, 'Music', 230);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (466, 'Film Studies', 187);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (467, 'Civil Engineering', 157);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (468, 'Public Health', 45);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (469, 'Linguistics', 137);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (470, 'Mechanical Engineering', 102);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (471, 'Counseling', 180);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (472, 'Biomedical Engineering', 176);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (473, 'Public Health', 146);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (474, 'Physics', 108);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (475, 'Mechanical Engineering', 192);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (476, 'Materials Science', 242);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (477, 'Business Administration', 50);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (478, 'Social Work', 49);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (479, 'Agricultural Science', 46);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (480, 'Agricultural Science', 27);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (481, 'Urban Planning', 209);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (482, 'Urban Planning', 244);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (483, 'Geology', 31);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (484, 'Criminal Justice', 21);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (485, 'Biology', 43);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (486, 'Linguistics', 205);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (487, 'Geography', 250);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (488, 'Sports Science', 121);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (489, 'Communications', 213);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (490, 'Public Health', 126);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (491, 'Kinesiology', 38);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (492, 'Mathematics', 141);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (493, 'Marketing', 166);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (494, 'Sports Science', 233);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (495, 'Geography', 162);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (496, 'Criminal Justice', 195);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (497, 'Biomedical Engineering', 134);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (498, 'Psychology', 44);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (499, 'Civil Engineering', 87);
insert into Faculty (idFaculty, faculty_name, idUniversity) values (500, 'Biology', 131);
