insert into Department (idDepartment, department_name, idFaculty) values (1, 'Civil Engineering', 313);
insert into Department (idDepartment, department_name, idFaculty) values (2, 'Brand Management', 136);
insert into Department (idDepartment, department_name, idFaculty) values (3, 'Molecular Biology', 347);
insert into Department (idDepartment, department_name, idFaculty) values (4, 'Agronomy', 52);
insert into Department (idDepartment, department_name, idFaculty) values (5, 'Aerospace Engineering', 133);
insert into Department (idDepartment, department_name, idFaculty) values (6, 'English Literature', 241);
insert into Department (idDepartment, department_name, idFaculty) values (7, 'Kinesiology', 341);
insert into Department (idDepartment, department_name, idFaculty) values (8, 'Biology', 95);
insert into Department (idDepartment, department_name, idFaculty) values (9, 'Sustainable Architecture', 309);
insert into Department (idDepartment, department_name, idFaculty) values (10, 'Mathematics', 485);
insert into Department (idDepartment, department_name, idFaculty) values (11, 'Entrepreneurship', 317);
insert into Department (idDepartment, department_name, idFaculty) values (12, 'Electrical Engineering', 161);
insert into Department (idDepartment, department_name, idFaculty) values (13, 'Computer Science', 343);
insert into Department (idDepartment, department_name, idFaculty) values (14, 'Environmental Science', 398);
insert into Department (idDepartment, department_name, idFaculty) values (15, 'Cultural Studies', 30);
insert into Department (idDepartment, department_name, idFaculty) values (16, 'Electrical Engineering', 307);
insert into Department (idDepartment, department_name, idFaculty) values (17, 'Aerospace Engineering', 431);
insert into Department (idDepartment, department_name, idFaculty) values (18, 'Special Education', 495);
insert into Department (idDepartment, department_name, idFaculty) values (19, 'Sculpture', 387);
insert into Department (idDepartment, department_name, idFaculty) values (20, 'Public Health', 367);
insert into Department (idDepartment, department_name, idFaculty) values (21, 'Mechanical Engineering', 133);
insert into Department (idDepartment, department_name, idFaculty) values (22, 'Quantum Mechanics', 492);
insert into Department (idDepartment, department_name, idFaculty) values (23, 'Ancient History', 159);
insert into Department (idDepartment, department_name, idFaculty) values (24, 'Drama', 184);
insert into Department (idDepartment, department_name, idFaculty) values (25, 'International Relations', 288);
insert into Department (idDepartment, department_name, idFaculty) values (26, 'Forensic Psychology', 37);
insert into Department (idDepartment, department_name, idFaculty) values (27, 'Mathematics', 158);
insert into Department (idDepartment, department_name, idFaculty) values (28, 'Molecular Biology', 402);
insert into Department (idDepartment, department_name, idFaculty) values (29, 'Creative Writing', 376);
insert into Department (idDepartment, department_name, idFaculty) values (30, 'Social Work', 500);
insert into Department (idDepartment, department_name, idFaculty) values (31, 'Creative Writing', 131);
insert into Department (idDepartment, department_name, idFaculty) values (32, 'Ethnomusicology', 417);
insert into Department (idDepartment, department_name, idFaculty) values (33, 'Business Administration', 386);
insert into Department (idDepartment, department_name, idFaculty) values (34, 'Electrical Engineering', 32);
insert into Department (idDepartment, department_name, idFaculty) values (35, 'History', 478);
insert into Department (idDepartment, department_name, idFaculty) values (36, 'Graphic Design', 128);
insert into Department (idDepartment, department_name, idFaculty) values (37, 'History', 485);
insert into Department (idDepartment, department_name, idFaculty) values (38, 'Counseling', 170);
insert into Department (idDepartment, department_name, idFaculty) values (39, 'Foreign Languages', 164);
insert into Department (idDepartment, department_name, idFaculty) values (40, 'Journalism', 193);
insert into Department (idDepartment, department_name, idFaculty) values (41, 'Criminal Justice', 104);
insert into Department (idDepartment, department_name, idFaculty) values (42, 'Special Education', 4);
insert into Department (idDepartment, department_name, idFaculty) values (43, 'Comparative Literature', 164);
insert into Department (idDepartment, department_name, idFaculty) values (44, 'Environmental Science', 43);
insert into Department (idDepartment, department_name, idFaculty) values (45, 'Anthropology', 425);
insert into Department (idDepartment, department_name, idFaculty) values (46, 'Special Education', 45);
insert into Department (idDepartment, department_name, idFaculty) values (47, 'Counseling', 12);
insert into Department (idDepartment, department_name, idFaculty) values (48, 'Ethnomusicology', 308);
insert into Department (idDepartment, department_name, idFaculty) values (49, 'Architecture', 107);
insert into Department (idDepartment, department_name, idFaculty) values (50, 'Biology', 104);
insert into Department (idDepartment, department_name, idFaculty) values (51, 'Business Administration', 109);
insert into Department (idDepartment, department_name, idFaculty) values (52, 'Brand Management', 82);
insert into Department (idDepartment, department_name, idFaculty) values (53, 'Marketing', 84);
insert into Department (idDepartment, department_name, idFaculty) values (54, 'Industrial Design', 4);
insert into Department (idDepartment, department_name, idFaculty) values (55, 'Ethics', 426);
insert into Department (idDepartment, department_name, idFaculty) values (56, 'Business Administration', 351);
insert into Department (idDepartment, department_name, idFaculty) values (57, 'Education', 359);
insert into Department (idDepartment, department_name, idFaculty) values (58, 'Human Resources', 324);
insert into Department (idDepartment, department_name, idFaculty) values (59, 'Electrical Engineering', 365);
insert into Department (idDepartment, department_name, idFaculty) values (60, 'Geography', 336);
insert into Department (idDepartment, department_name, idFaculty) values (61, 'Agronomy', 136);
insert into Department (idDepartment, department_name, idFaculty) values (62, 'Media Studies', 460);
insert into Department (idDepartment, department_name, idFaculty) values (63, 'Psychology', 165);
insert into Department (idDepartment, department_name, idFaculty) values (64, 'Quantum Mechanics', 164);
insert into Department (idDepartment, department_name, idFaculty) values (65, 'American Literature', 499);
insert into Department (idDepartment, department_name, idFaculty) values (66, 'Innovation', 414);
insert into Department (idDepartment, department_name, idFaculty) values (67, 'Graphic Design', 402);
insert into Department (idDepartment, department_name, idFaculty) values (68, 'Geography', 440);
insert into Department (idDepartment, department_name, idFaculty) values (69, 'Archaeological Anthropology', 106);
insert into Department (idDepartment, department_name, idFaculty) values (70, 'Quantum Mechanics', 28);
insert into Department (idDepartment, department_name, idFaculty) values (71, 'Forensic Science', 113);
insert into Department (idDepartment, department_name, idFaculty) values (72, 'Music', 15);
insert into Department (idDepartment, department_name, idFaculty) values (73, 'Pediatric Nursing', 93);
insert into Department (idDepartment, department_name, idFaculty) values (74, 'Ancient History', 272);
insert into Department (idDepartment, department_name, idFaculty) values (75, 'Ancient History', 181);
insert into Department (idDepartment, department_name, idFaculty) values (76, 'Agronomy', 309);
insert into Department (idDepartment, department_name, idFaculty) values (77, 'Music', 303);
insert into Department (idDepartment, department_name, idFaculty) values (78, 'Renewable Energy Engineering', 267);
insert into Department (idDepartment, department_name, idFaculty) values (79, 'Behavioral Economics', 388);
insert into Department (idDepartment, department_name, idFaculty) values (80, 'Ethics', 210);
insert into Department (idDepartment, department_name, idFaculty) values (81, 'Cognitive Psychology', 320);
insert into Department (idDepartment, department_name, idFaculty) values (82, 'Cryptography', 369);
insert into Department (idDepartment, department_name, idFaculty) values (83, 'Ethics', 433);
insert into Department (idDepartment, department_name, idFaculty) values (84, 'Anthropology', 214);
insert into Department (idDepartment, department_name, idFaculty) values (85, 'Entrepreneurship', 238);
insert into Department (idDepartment, department_name, idFaculty) values (86, 'Electrical Engineering', 43);
insert into Department (idDepartment, department_name, idFaculty) values (87, 'Astrophysics', 332);
insert into Department (idDepartment, department_name, idFaculty) values (88, 'Cultural Studies', 346);
insert into Department (idDepartment, department_name, idFaculty) values (89, 'Industrial Design Engineering', 109);
insert into Department (idDepartment, department_name, idFaculty) values (90, 'Nursing', 272);
insert into Department (idDepartment, department_name, idFaculty) values (91, 'Counseling', 453);
insert into Department (idDepartment, department_name, idFaculty) values (92, 'History', 362);
insert into Department (idDepartment, department_name, idFaculty) values (93, 'Physics', 77);
insert into Department (idDepartment, department_name, idFaculty) values (94, 'Aerospace Engineering', 15);
insert into Department (idDepartment, department_name, idFaculty) values (95, 'Philosophy', 380);
insert into Department (idDepartment, department_name, idFaculty) values (96, 'Network Security', 72);
insert into Department (idDepartment, department_name, idFaculty) values (97, 'Drama', 418);
insert into Department (idDepartment, department_name, idFaculty) values (98, 'Computer Science', 273);
insert into Department (idDepartment, department_name, idFaculty) values (99, 'Forensic Science', 384);
insert into Department (idDepartment, department_name, idFaculty) values (100, 'Cryptography', 87);
insert into Department (idDepartment, department_name, idFaculty) values (101, 'Nutrition', 491);
insert into Department (idDepartment, department_name, idFaculty) values (102, 'Religious Studies', 297);
insert into Department (idDepartment, department_name, idFaculty) values (103, 'Urban Sociology', 346);
insert into Department (idDepartment, department_name, idFaculty) values (104, 'Polymer Chemistry', 314);
insert into Department (idDepartment, department_name, idFaculty) values (105, 'Media Studies', 77);
insert into Department (idDepartment, department_name, idFaculty) values (106, 'Biomedical Engineering', 30);
insert into Department (idDepartment, department_name, idFaculty) values (107, 'Sustainable Architecture', 392);
insert into Department (idDepartment, department_name, idFaculty) values (108, 'Veterinary Science', 347);
insert into Department (idDepartment, department_name, idFaculty) values (109, 'Education', 336);
insert into Department (idDepartment, department_name, idFaculty) values (110, 'Brand Management', 484);
insert into Department (idDepartment, department_name, idFaculty) values (111, 'Pediatric Nursing', 345);
insert into Department (idDepartment, department_name, idFaculty) values (112, 'Criminal Justice', 269);
insert into Department (idDepartment, department_name, idFaculty) values (113, 'Entrepreneurship', 256);
insert into Department (idDepartment, department_name, idFaculty) values (114, 'Environmental Policy', 43);
insert into Department (idDepartment, department_name, idFaculty) values (115, 'Nursing', 500);
insert into Department (idDepartment, department_name, idFaculty) values (116, 'Entrepreneurship', 357);
insert into Department (idDepartment, department_name, idFaculty) values (117, 'Public Health', 311);
insert into Department (idDepartment, department_name, idFaculty) values (118, 'Materials Science', 40);
insert into Department (idDepartment, department_name, idFaculty) values (119, 'Fine Arts', 491);
insert into Department (idDepartment, department_name, idFaculty) values (120, 'Industrial Design', 198);
insert into Department (idDepartment, department_name, idFaculty) values (121, 'Fine Arts', 355);
insert into Department (idDepartment, department_name, idFaculty) values (122, 'Social Work', 222);
insert into Department (idDepartment, department_name, idFaculty) values (123, 'Materials Science', 394);
insert into Department (idDepartment, department_name, idFaculty) values (124, 'Geography', 128);
insert into Department (idDepartment, department_name, idFaculty) values (125, 'Global Health', 153);
insert into Department (idDepartment, department_name, idFaculty) values (126, 'Human Resources', 384);
insert into Department (idDepartment, department_name, idFaculty) values (127, 'Molecular Biology', 187);
insert into Department (idDepartment, department_name, idFaculty) values (128, 'Philosophy', 253);
insert into Department (idDepartment, department_name, idFaculty) values (129, 'Forensic Science', 118);
insert into Department (idDepartment, department_name, idFaculty) values (130, 'Structural Engineering', 6);
insert into Department (idDepartment, department_name, idFaculty) values (131, 'Foreign Languages', 274);
insert into Department (idDepartment, department_name, idFaculty) values (132, 'Comparative Literature', 117);
insert into Department (idDepartment, department_name, idFaculty) values (133, 'Agronomy', 271);
insert into Department (idDepartment, department_name, idFaculty) values (134, 'Music', 75);
insert into Department (idDepartment, department_name, idFaculty) values (135, 'Molecular Biology', 57);
insert into Department (idDepartment, department_name, idFaculty) values (136, 'Criminal Justice', 275);
insert into Department (idDepartment, department_name, idFaculty) values (137, 'Comparative Literature', 1);
insert into Department (idDepartment, department_name, idFaculty) values (138, 'Forensic Science', 472);
insert into Department (idDepartment, department_name, idFaculty) values (139, 'Agricultural Science', 73);
insert into Department (idDepartment, department_name, idFaculty) values (140, 'Quantum Mechanics', 121);
insert into Department (idDepartment, department_name, idFaculty) values (141, 'Cultural Studies', 162);
insert into Department (idDepartment, department_name, idFaculty) values (142, 'Geography', 270);
insert into Department (idDepartment, department_name, idFaculty) values (143, 'Veterinary Science', 295);
insert into Department (idDepartment, department_name, idFaculty) values (144, 'Mechanical Engineering', 49);
insert into Department (idDepartment, department_name, idFaculty) values (145, 'Drama', 392);
insert into Department (idDepartment, department_name, idFaculty) values (146, 'Agronomy', 66);
insert into Department (idDepartment, department_name, idFaculty) values (147, 'Human Resources', 270);
insert into Department (idDepartment, department_name, idFaculty) values (148, 'Human Resources', 123);
insert into Department (idDepartment, department_name, idFaculty) values (149, 'Social Work', 361);
insert into Department (idDepartment, department_name, idFaculty) values (150, 'Urban Sociology', 200);
insert into Department (idDepartment, department_name, idFaculty) values (151, 'Film Studies', 237);
insert into Department (idDepartment, department_name, idFaculty) values (152, 'Anthropology', 350);
insert into Department (idDepartment, department_name, idFaculty) values (153, 'Entrepreneurship', 180);
insert into Department (idDepartment, department_name, idFaculty) values (154, 'Urban Planning', 34);
insert into Department (idDepartment, department_name, idFaculty) values (155, 'Anthropology', 394);
insert into Department (idDepartment, department_name, idFaculty) values (156, 'Veterinary Science', 83);
insert into Department (idDepartment, department_name, idFaculty) values (157, 'Forensic Psychology', 22);
insert into Department (idDepartment, department_name, idFaculty) values (158, 'Aerospace Engineering', 314);
insert into Department (idDepartment, department_name, idFaculty) values (159, 'Geography', 124);
insert into Department (idDepartment, department_name, idFaculty) values (160, 'Mathematics', 406);
insert into Department (idDepartment, department_name, idFaculty) values (161, 'Urban Sociology', 169);
insert into Department (idDepartment, department_name, idFaculty) values (162, 'Human Resources', 62);
insert into Department (idDepartment, department_name, idFaculty) values (163, 'Business Administration', 450);
insert into Department (idDepartment, department_name, idFaculty) values (164, 'Entrepreneurship', 228);
insert into Department (idDepartment, department_name, idFaculty) values (165, 'Political Science', 334);
insert into Department (idDepartment, department_name, idFaculty) values (166, 'Philosophy', 444);
insert into Department (idDepartment, department_name, idFaculty) values (167, 'Agricultural Science', 178);
insert into Department (idDepartment, department_name, idFaculty) values (168, 'Brand Management', 199);
insert into Department (idDepartment, department_name, idFaculty) values (169, 'Media Studies', 30);
insert into Department (idDepartment, department_name, idFaculty) values (170, 'Astrophysics', 190);
insert into Department (idDepartment, department_name, idFaculty) values (171, 'Quantum Mechanics', 255);
insert into Department (idDepartment, department_name, idFaculty) values (172, 'Volcanology', 112);
insert into Department (idDepartment, department_name, idFaculty) values (173, 'Special Education', 284);
insert into Department (idDepartment, department_name, idFaculty) values (174, 'Anthropology', 39);
insert into Department (idDepartment, department_name, idFaculty) values (175, 'Chemistry', 313);
insert into Department (idDepartment, department_name, idFaculty) values (176, 'Urban Planning', 250);
insert into Department (idDepartment, department_name, idFaculty) values (177, 'Pediatric Nursing', 50);
insert into Department (idDepartment, department_name, idFaculty) values (178, 'Communications', 247);
insert into Department (idDepartment, department_name, idFaculty) values (179, 'Structural Engineering', 94);
insert into Department (idDepartment, department_name, idFaculty) values (180, 'Industrial Design Engineering', 155);
insert into Department (idDepartment, department_name, idFaculty) values (181, 'Veterinary Science', 79);
insert into Department (idDepartment, department_name, idFaculty) values (182, 'Graphic Design', 362);
insert into Department (idDepartment, department_name, idFaculty) values (183, 'Urban Sociology', 283);
insert into Department (idDepartment, department_name, idFaculty) values (184, 'Entrepreneurship', 381);
insert into Department (idDepartment, department_name, idFaculty) values (185, 'Behavioral Economics', 298);
insert into Department (idDepartment, department_name, idFaculty) values (186, 'Nutrition', 148);
insert into Department (idDepartment, department_name, idFaculty) values (187, 'Mathematics', 395);
insert into Department (idDepartment, department_name, idFaculty) values (188, 'Organic Chemistry', 79);
insert into Department (idDepartment, department_name, idFaculty) values (189, 'Sports Science', 427);
insert into Department (idDepartment, department_name, idFaculty) values (190, 'Foreign Languages', 270);
insert into Department (idDepartment, department_name, idFaculty) values (191, 'Sustainable Architecture', 304);
insert into Department (idDepartment, department_name, idFaculty) values (192, 'Computer Science', 11);
insert into Department (idDepartment, department_name, idFaculty) values (193, 'Agronomy', 101);
insert into Department (idDepartment, department_name, idFaculty) values (194, 'Mathematics', 218);
insert into Department (idDepartment, department_name, idFaculty) values (195, 'Crop Science', 236);
insert into Department (idDepartment, department_name, idFaculty) values (196, 'Cultural Studies', 96);
insert into Department (idDepartment, department_name, idFaculty) values (197, 'Forensic Science', 284);
insert into Department (idDepartment, department_name, idFaculty) values (198, 'Agronomy', 351);
insert into Department (idDepartment, department_name, idFaculty) values (199, 'Architecture', 275);
insert into Department (idDepartment, department_name, idFaculty) values (200, 'Crop Science', 183);
insert into Department (idDepartment, department_name, idFaculty) values (201, 'Volcanology', 47);
insert into Department (idDepartment, department_name, idFaculty) values (202, 'Sports Science', 497);
insert into Department (idDepartment, department_name, idFaculty) values (203, 'Education', 181);
insert into Department (idDepartment, department_name, idFaculty) values (204, 'Cryptography', 438);
insert into Department (idDepartment, department_name, idFaculty) values (205, 'Creative Writing', 38);
insert into Department (idDepartment, department_name, idFaculty) values (206, 'Comparative Literature', 431);
insert into Department (idDepartment, department_name, idFaculty) values (207, 'Communications', 36);
insert into Department (idDepartment, department_name, idFaculty) values (208, 'Innovation', 131);
insert into Department (idDepartment, department_name, idFaculty) values (209, 'Cryptography', 251);
insert into Department (idDepartment, department_name, idFaculty) values (210, 'Agronomy', 149);
insert into Department (idDepartment, department_name, idFaculty) values (211, 'Religious Studies', 297);
insert into Department (idDepartment, department_name, idFaculty) values (212, 'Public Health', 292);
insert into Department (idDepartment, department_name, idFaculty) values (213, 'Polymer Chemistry', 56);
insert into Department (idDepartment, department_name, idFaculty) values (214, 'Cognitive Psychology', 86);
insert into Department (idDepartment, department_name, idFaculty) values (215, 'Graphic Design', 136);
insert into Department (idDepartment, department_name, idFaculty) values (216, 'Urban Sociology', 303);
insert into Department (idDepartment, department_name, idFaculty) values (217, 'Biomedical Engineering', 449);
insert into Department (idDepartment, department_name, idFaculty) values (218, 'Linguistics', 440);
insert into Department (idDepartment, department_name, idFaculty) values (219, 'Marketing', 350);
insert into Department (idDepartment, department_name, idFaculty) values (220, 'Kinesiology', 68);
insert into Department (idDepartment, department_name, idFaculty) values (221, 'Nutrition', 435);
insert into Department (idDepartment, department_name, idFaculty) values (222, 'Biomedical Engineering', 122);
insert into Department (idDepartment, department_name, idFaculty) values (223, 'Marketing', 59);
insert into Department (idDepartment, department_name, idFaculty) values (224, 'Electrical Engineering', 87);
insert into Department (idDepartment, department_name, idFaculty) values (225, 'Drama', 421);
insert into Department (idDepartment, department_name, idFaculty) values (226, 'Creative Writing', 3);
insert into Department (idDepartment, department_name, idFaculty) values (227, 'Environmental Policy', 499);
insert into Department (idDepartment, department_name, idFaculty) values (228, 'Renewable Energy Engineering', 201);
insert into Department (idDepartment, department_name, idFaculty) values (229, 'Religious Studies', 452);
insert into Department (idDepartment, department_name, idFaculty) values (230, 'Artificial Intelligence', 147);
insert into Department (idDepartment, department_name, idFaculty) values (231, 'Music', 130);
insert into Department (idDepartment, department_name, idFaculty) values (232, 'Communications', 476);
insert into Department (idDepartment, department_name, idFaculty) values (233, 'Sociology', 334);
insert into Department (idDepartment, department_name, idFaculty) values (234, 'Social Work', 213);
insert into Department (idDepartment, department_name, idFaculty) values (235, 'Education', 95);
insert into Department (idDepartment, department_name, idFaculty) values (236, 'Communications', 474);
insert into Department (idDepartment, department_name, idFaculty) values (237, 'Sculpture', 328);
insert into Department (idDepartment, department_name, idFaculty) values (238, 'Media Studies', 261);
insert into Department (idDepartment, department_name, idFaculty) values (239, 'Electrical Engineering', 112);
insert into Department (idDepartment, department_name, idFaculty) values (240, 'Environmental Science', 456);
insert into Department (idDepartment, department_name, idFaculty) values (241, 'Special Education', 435);
insert into Department (idDepartment, department_name, idFaculty) values (242, 'Polymer Chemistry', 198);
insert into Department (idDepartment, department_name, idFaculty) values (243, 'Agronomy', 108);
insert into Department (idDepartment, department_name, idFaculty) values (244, 'Materials Science', 17);
insert into Department (idDepartment, department_name, idFaculty) values (245, 'Veterinary Science', 447);
insert into Department (idDepartment, department_name, idFaculty) values (246, 'Innovation', 326);
insert into Department (idDepartment, department_name, idFaculty) values (247, 'Civil Engineering', 305);
insert into Department (idDepartment, department_name, idFaculty) values (248, 'American Literature', 259);
insert into Department (idDepartment, department_name, idFaculty) values (249, 'Chemistry', 72);
insert into Department (idDepartment, department_name, idFaculty) values (250, 'International Relations', 236);
insert into Department (idDepartment, department_name, idFaculty) values (251, 'Brand Management', 67);
insert into Department (idDepartment, department_name, idFaculty) values (252, 'Biology', 220);
insert into Department (idDepartment, department_name, idFaculty) values (253, 'Environmental Policy', 156);
insert into Department (idDepartment, department_name, idFaculty) values (254, 'Industrial Design', 461);
insert into Department (idDepartment, department_name, idFaculty) values (255, 'Artificial Intelligence', 101);
insert into Department (idDepartment, department_name, idFaculty) values (256, 'Agricultural Science', 448);
insert into Department (idDepartment, department_name, idFaculty) values (257, 'Artificial Intelligence', 5);
insert into Department (idDepartment, department_name, idFaculty) values (258, 'Biomedical Engineering', 403);
insert into Department (idDepartment, department_name, idFaculty) values (259, 'Biomedical Engineering', 500);
insert into Department (idDepartment, department_name, idFaculty) values (260, 'Cryptography', 272);
insert into Department (idDepartment, department_name, idFaculty) values (261, 'Nursing', 151);
insert into Department (idDepartment, department_name, idFaculty) values (262, 'Organic Chemistry', 249);
insert into Department (idDepartment, department_name, idFaculty) values (263, 'American Literature', 313);
insert into Department (idDepartment, department_name, idFaculty) values (264, 'Ethnomusicology', 226);
insert into Department (idDepartment, department_name, idFaculty) values (265, 'Sociology', 67);
insert into Department (idDepartment, department_name, idFaculty) values (266, 'Comparative Literature', 203);
insert into Department (idDepartment, department_name, idFaculty) values (267, 'Mathematics', 413);
insert into Department (idDepartment, department_name, idFaculty) values (268, 'Veterinary Science', 269);
insert into Department (idDepartment, department_name, idFaculty) values (269, 'Molecular Biology', 341);
insert into Department (idDepartment, department_name, idFaculty) values (270, 'Public Health', 250);
insert into Department (idDepartment, department_name, idFaculty) values (271, 'Ethics', 225);
insert into Department (idDepartment, department_name, idFaculty) values (272, 'Marketing', 327);
insert into Department (idDepartment, department_name, idFaculty) values (273, 'Media Studies', 479);
insert into Department (idDepartment, department_name, idFaculty) values (274, 'Biomedical Engineering', 186);
insert into Department (idDepartment, department_name, idFaculty) values (275, 'International Relations', 101);
insert into Department (idDepartment, department_name, idFaculty) values (276, 'Sports Science', 111);
insert into Department (idDepartment, department_name, idFaculty) values (277, 'Physics', 174);
insert into Department (idDepartment, department_name, idFaculty) values (278, 'Forensic Science', 149);
insert into Department (idDepartment, department_name, idFaculty) values (279, 'Forensic Science', 126);
insert into Department (idDepartment, department_name, idFaculty) values (280, 'Linguistics', 120);
insert into Department (idDepartment, department_name, idFaculty) values (281, 'Chemistry', 482);
insert into Department (idDepartment, department_name, idFaculty) values (282, 'Materials Science', 304);
insert into Department (idDepartment, department_name, idFaculty) values (283, 'Communications', 115);
insert into Department (idDepartment, department_name, idFaculty) values (284, 'Sociology', 198);
insert into Department (idDepartment, department_name, idFaculty) values (285, 'Ancient History', 350);
insert into Department (idDepartment, department_name, idFaculty) values (286, 'Physics', 279);
insert into Department (idDepartment, department_name, idFaculty) values (287, 'Physics', 73);
insert into Department (idDepartment, department_name, idFaculty) values (288, 'Social Work', 176);
insert into Department (idDepartment, department_name, idFaculty) values (289, 'Mechanical Engineering', 316);
insert into Department (idDepartment, department_name, idFaculty) values (290, 'Environmental Science', 199);
insert into Department (idDepartment, department_name, idFaculty) values (291, 'Music', 150);
insert into Department (idDepartment, department_name, idFaculty) values (292, 'Psychology', 208);
insert into Department (idDepartment, department_name, idFaculty) values (293, 'Comparative Literature', 351);
insert into Department (idDepartment, department_name, idFaculty) values (294, 'Astrophysics', 188);
insert into Department (idDepartment, department_name, idFaculty) values (295, 'Mechanical Engineering', 455);
insert into Department (idDepartment, department_name, idFaculty) values (296, 'Volcanology', 241);
insert into Department (idDepartment, department_name, idFaculty) values (297, 'Ethics', 409);
insert into Department (idDepartment, department_name, idFaculty) values (298, 'Behavioral Economics', 286);
insert into Department (idDepartment, department_name, idFaculty) values (299, 'Business Administration', 435);
insert into Department (idDepartment, department_name, idFaculty) values (300, 'Computer Science', 165);
insert into Department (idDepartment, department_name, idFaculty) values (301, 'Fine Arts', 483);
insert into Department (idDepartment, department_name, idFaculty) values (302, 'Environmental Policy', 205);
insert into Department (idDepartment, department_name, idFaculty) values (303, 'Biology', 297);
insert into Department (idDepartment, department_name, idFaculty) values (304, 'Physics', 158);
insert into Department (idDepartment, department_name, idFaculty) values (305, 'Nursing', 307);
insert into Department (idDepartment, department_name, idFaculty) values (306, 'Sociology', 58);
insert into Department (idDepartment, department_name, idFaculty) values (307, 'American Literature', 313);
insert into Department (idDepartment, department_name, idFaculty) values (308, 'Entrepreneurship', 33);
insert into Department (idDepartment, department_name, idFaculty) values (309, 'Agricultural Science', 473);
insert into Department (idDepartment, department_name, idFaculty) values (310, 'Pediatric Nursing', 400);
insert into Department (idDepartment, department_name, idFaculty) values (311, 'Anthropology', 488);
insert into Department (idDepartment, department_name, idFaculty) values (312, 'Industrial Design', 72);
insert into Department (idDepartment, department_name, idFaculty) values (313, 'Environmental Science', 474);
insert into Department (idDepartment, department_name, idFaculty) values (314, 'Geography', 63);
insert into Department (idDepartment, department_name, idFaculty) values (315, 'Communications', 461);
insert into Department (idDepartment, department_name, idFaculty) values (316, 'Social Work', 369);
insert into Department (idDepartment, department_name, idFaculty) values (317, 'Religious Studies', 500);
insert into Department (idDepartment, department_name, idFaculty) values (318, 'Ethics', 189);
insert into Department (idDepartment, department_name, idFaculty) values (319, 'Astrophysics', 222);
insert into Department (idDepartment, department_name, idFaculty) values (320, 'Counseling', 104);
insert into Department (idDepartment, department_name, idFaculty) values (321, 'Archaeological Anthropology', 336);
insert into Department (idDepartment, department_name, idFaculty) values (322, 'Cognitive Psychology', 149);
insert into Department (idDepartment, department_name, idFaculty) values (323, 'Anthropology', 223);
insert into Department (idDepartment, department_name, idFaculty) values (324, 'Quantum Mechanics', 293);
insert into Department (idDepartment, department_name, idFaculty) values (325, 'Comparative Literature', 449);
insert into Department (idDepartment, department_name, idFaculty) values (326, 'Mechanical Engineering', 122);
insert into Department (idDepartment, department_name, idFaculty) values (327, 'Ethics', 286);
insert into Department (idDepartment, department_name, idFaculty) values (328, 'Industrial Design Engineering', 3);
insert into Department (idDepartment, department_name, idFaculty) values (329, 'Linguistics', 401);
insert into Department (idDepartment, department_name, idFaculty) values (330, 'Aerospace Engineering', 483);
insert into Department (idDepartment, department_name, idFaculty) values (331, 'Electrical Engineering', 77);
insert into Department (idDepartment, department_name, idFaculty) values (332, 'Comparative Literature', 166);
insert into Department (idDepartment, department_name, idFaculty) values (333, 'Forensic Science', 211);
insert into Department (idDepartment, department_name, idFaculty) values (334, 'Drama', 140);
insert into Department (idDepartment, department_name, idFaculty) values (335, 'Marketing', 429);
insert into Department (idDepartment, department_name, idFaculty) values (336, 'Brand Management', 247);
insert into Department (idDepartment, department_name, idFaculty) values (337, 'Film Studies', 9);
insert into Department (idDepartment, department_name, idFaculty) values (338, 'Public Health', 149);
insert into Department (idDepartment, department_name, idFaculty) values (339, 'Fine Arts', 273);
insert into Department (idDepartment, department_name, idFaculty) values (340, 'Economics', 12);
insert into Department (idDepartment, department_name, idFaculty) values (341, 'Structural Engineering', 162);
insert into Department (idDepartment, department_name, idFaculty) values (342, 'Criminal Justice', 123);
insert into Department (idDepartment, department_name, idFaculty) values (343, 'Sports Nutrition', 49);
insert into Department (idDepartment, department_name, idFaculty) values (344, 'Innovation', 255);
insert into Department (idDepartment, department_name, idFaculty) values (345, 'Religious Studies', 475);
insert into Department (idDepartment, department_name, idFaculty) values (346, 'Veterinary Science', 351);
insert into Department (idDepartment, department_name, idFaculty) values (347, 'Architecture', 154);
insert into Department (idDepartment, department_name, idFaculty) values (348, 'Moral Philosophy', 124);
insert into Department (idDepartment, department_name, idFaculty) values (349, 'Business Administration', 185);
insert into Department (idDepartment, department_name, idFaculty) values (350, 'Renewable Energy Engineering', 371);
insert into Department (idDepartment, department_name, idFaculty) values (351, 'Social Work', 472);
insert into Department (idDepartment, department_name, idFaculty) values (352, 'American Literature', 322);
insert into Department (idDepartment, department_name, idFaculty) values (353, 'Ancient History', 215);
insert into Department (idDepartment, department_name, idFaculty) values (354, 'Geology', 201);
insert into Department (idDepartment, department_name, idFaculty) values (355, 'Archaeological Anthropology', 24);
insert into Department (idDepartment, department_name, idFaculty) values (356, 'Counseling', 258);
insert into Department (idDepartment, department_name, idFaculty) values (357, 'Urban Sociology', 370);
insert into Department (idDepartment, department_name, idFaculty) values (358, 'Marketing', 363);
insert into Department (idDepartment, department_name, idFaculty) values (359, 'Music', 62);
insert into Department (idDepartment, department_name, idFaculty) values (360, 'Graphic Design', 86);
insert into Department (idDepartment, department_name, idFaculty) values (361, 'Sports Science', 128);
insert into Department (idDepartment, department_name, idFaculty) values (362, 'Aerospace Engineering', 277);
insert into Department (idDepartment, department_name, idFaculty) values (363, 'Behavioral Economics', 237);
insert into Department (idDepartment, department_name, idFaculty) values (364, 'Sociology', 437);
insert into Department (idDepartment, department_name, idFaculty) values (365, 'Astrophysics', 381);
insert into Department (idDepartment, department_name, idFaculty) values (366, 'Ancient History', 426);
insert into Department (idDepartment, department_name, idFaculty) values (367, 'Ethnomusicology', 306);
insert into Department (idDepartment, department_name, idFaculty) values (368, 'Structural Engineering', 306);
insert into Department (idDepartment, department_name, idFaculty) values (369, 'International Relations', 58);
insert into Department (idDepartment, department_name, idFaculty) values (370, 'Education', 326);
insert into Department (idDepartment, department_name, idFaculty) values (371, 'Mechanical Engineering', 344);
insert into Department (idDepartment, department_name, idFaculty) values (372, 'Nutrition', 60);
insert into Department (idDepartment, department_name, idFaculty) values (373, 'Physics', 257);
insert into Department (idDepartment, department_name, idFaculty) values (374, 'Creative Writing', 180);
insert into Department (idDepartment, department_name, idFaculty) values (375, 'Molecular Biology', 372);
insert into Department (idDepartment, department_name, idFaculty) values (376, 'Graphic Design', 364);
insert into Department (idDepartment, department_name, idFaculty) values (377, 'Cryptography', 255);
insert into Department (idDepartment, department_name, idFaculty) values (378, 'English Literature', 192);
insert into Department (idDepartment, department_name, idFaculty) values (379, 'English Literature', 174);
insert into Department (idDepartment, department_name, idFaculty) values (380, 'Ancient History', 71);
insert into Department (idDepartment, department_name, idFaculty) values (381, 'Psychology', 245);
insert into Department (idDepartment, department_name, idFaculty) values (382, 'Moral Philosophy', 149);
insert into Department (idDepartment, department_name, idFaculty) values (383, 'Civil Engineering', 37);
insert into Department (idDepartment, department_name, idFaculty) values (384, 'Public Health', 5);
insert into Department (idDepartment, department_name, idFaculty) values (385, 'Pediatric Nursing', 74);
insert into Department (idDepartment, department_name, idFaculty) values (386, 'Cryptography', 94);
insert into Department (idDepartment, department_name, idFaculty) values (387, 'Human Resources', 73);
insert into Department (idDepartment, department_name, idFaculty) values (388, 'Urban Planning', 378);
insert into Department (idDepartment, department_name, idFaculty) values (389, 'Biomedical Engineering', 143);
insert into Department (idDepartment, department_name, idFaculty) values (390, 'Cognitive Psychology', 63);
insert into Department (idDepartment, department_name, idFaculty) values (391, 'Polymer Chemistry', 24);
insert into Department (idDepartment, department_name, idFaculty) values (392, 'Computer Science', 97);
insert into Department (idDepartment, department_name, idFaculty) values (393, 'Nutrition', 296);
insert into Department (idDepartment, department_name, idFaculty) values (394, 'Quantum Mechanics', 267);
insert into Department (idDepartment, department_name, idFaculty) values (395, 'Urban Planning', 497);
insert into Department (idDepartment, department_name, idFaculty) values (396, 'Urban Planning', 195);
insert into Department (idDepartment, department_name, idFaculty) values (397, 'Environmental Science', 352);
insert into Department (idDepartment, department_name, idFaculty) values (398, 'Brand Management', 70);
insert into Department (idDepartment, department_name, idFaculty) values (399, 'Global Health', 489);
insert into Department (idDepartment, department_name, idFaculty) values (400, 'Crop Science', 437);
insert into Department (idDepartment, department_name, idFaculty) values (401, 'Environmental Policy', 236);
insert into Department (idDepartment, department_name, idFaculty) values (402, 'Journalism', 45);
insert into Department (idDepartment, department_name, idFaculty) values (403, 'Nursing', 201);
insert into Department (idDepartment, department_name, idFaculty) values (404, 'Cryptography', 10);
insert into Department (idDepartment, department_name, idFaculty) values (405, 'Crop Science', 77);
insert into Department (idDepartment, department_name, idFaculty) values (406, 'Religious Studies', 440);
insert into Department (idDepartment, department_name, idFaculty) values (407, 'English Literature', 311);
insert into Department (idDepartment, department_name, idFaculty) values (408, 'Veterinary Science', 135);
insert into Department (idDepartment, department_name, idFaculty) values (409, 'Geology', 173);
insert into Department (idDepartment, department_name, idFaculty) values (410, 'Religious Studies', 168);
insert into Department (idDepartment, department_name, idFaculty) values (411, 'Public Health', 36);
insert into Department (idDepartment, department_name, idFaculty) values (412, 'Sports Nutrition', 155);
insert into Department (idDepartment, department_name, idFaculty) values (413, 'Cultural Studies', 439);
insert into Department (idDepartment, department_name, idFaculty) values (414, 'Polymer Chemistry', 111);
insert into Department (idDepartment, department_name, idFaculty) values (415, 'Industrial Design Engineering', 232);
insert into Department (idDepartment, department_name, idFaculty) values (416, 'Sports Nutrition', 289);
insert into Department (idDepartment, department_name, idFaculty) values (417, 'Cryptography', 184);
insert into Department (idDepartment, department_name, idFaculty) values (418, 'Biomedical Engineering', 423);
insert into Department (idDepartment, department_name, idFaculty) values (419, 'Film Studies', 397);
insert into Department (idDepartment, department_name, idFaculty) values (420, 'Geography', 48);
insert into Department (idDepartment, department_name, idFaculty) values (421, 'Civil Engineering', 376);
insert into Department (idDepartment, department_name, idFaculty) values (422, 'Aerospace Engineering', 301);
insert into Department (idDepartment, department_name, idFaculty) values (423, 'Geology', 324);
insert into Department (idDepartment, department_name, idFaculty) values (424, 'Crop Science', 462);
insert into Department (idDepartment, department_name, idFaculty) values (425, 'Film Studies', 337);
insert into Department (idDepartment, department_name, idFaculty) values (426, 'Geology', 141);
insert into Department (idDepartment, department_name, idFaculty) values (427, 'Marketing', 145);
insert into Department (idDepartment, department_name, idFaculty) values (428, 'Moral Philosophy', 254);
insert into Department (idDepartment, department_name, idFaculty) values (429, 'Chemistry', 382);
insert into Department (idDepartment, department_name, idFaculty) values (430, 'Cryptography', 42);
insert into Department (idDepartment, department_name, idFaculty) values (431, 'Moral Philosophy', 273);
insert into Department (idDepartment, department_name, idFaculty) values (432, 'Foreign Languages', 291);
insert into Department (idDepartment, department_name, idFaculty) values (433, 'Ancient History', 332);
insert into Department (idDepartment, department_name, idFaculty) values (434, 'Communications', 196);
insert into Department (idDepartment, department_name, idFaculty) values (435, 'Urban Planning', 152);
insert into Department (idDepartment, department_name, idFaculty) values (436, 'Chemistry', 127);
insert into Department (idDepartment, department_name, idFaculty) values (437, 'Communications', 289);
insert into Department (idDepartment, department_name, idFaculty) values (438, 'Marketing', 490);
insert into Department (idDepartment, department_name, idFaculty) values (439, 'Nursing', 119);
insert into Department (idDepartment, department_name, idFaculty) values (440, 'Moral Philosophy', 461);
insert into Department (idDepartment, department_name, idFaculty) values (441, 'Philosophy', 1);
insert into Department (idDepartment, department_name, idFaculty) values (442, 'Geology', 225);
insert into Department (idDepartment, department_name, idFaculty) values (443, 'Quantum Mechanics', 466);
insert into Department (idDepartment, department_name, idFaculty) values (444, 'Industrial Design', 86);
insert into Department (idDepartment, department_name, idFaculty) values (445, 'Archaeological Anthropology', 447);
insert into Department (idDepartment, department_name, idFaculty) values (446, 'Molecular Biology', 265);
insert into Department (idDepartment, department_name, idFaculty) values (447, 'Artificial Intelligence', 273);
insert into Department (idDepartment, department_name, idFaculty) values (448, 'Human Resources', 108);
insert into Department (idDepartment, department_name, idFaculty) values (449, 'International Relations', 395);
insert into Department (idDepartment, department_name, idFaculty) values (450, 'Public Health', 382);
insert into Department (idDepartment, department_name, idFaculty) values (451, 'Mechanical Engineering', 159);
insert into Department (idDepartment, department_name, idFaculty) values (452, 'Materials Science', 352);
insert into Department (idDepartment, department_name, idFaculty) values (453, 'American Literature', 426);
insert into Department (idDepartment, department_name, idFaculty) values (454, 'Archaeological Anthropology', 31);
insert into Department (idDepartment, department_name, idFaculty) values (455, 'Urban Planning', 469);
insert into Department (idDepartment, department_name, idFaculty) values (456, 'Archaeological Anthropology', 276);
insert into Department (idDepartment, department_name, idFaculty) values (457, 'International Relations', 348);
insert into Department (idDepartment, department_name, idFaculty) values (458, 'English Literature', 295);
insert into Department (idDepartment, department_name, idFaculty) values (459, 'Ancient History', 197);
insert into Department (idDepartment, department_name, idFaculty) values (460, 'Molecular Biology', 145);
insert into Department (idDepartment, department_name, idFaculty) values (461, 'Media Studies', 290);
insert into Department (idDepartment, department_name, idFaculty) values (462, 'Computer Science', 247);
insert into Department (idDepartment, department_name, idFaculty) values (463, 'Forensic Psychology', 27);
insert into Department (idDepartment, department_name, idFaculty) values (464, 'Mechanical Engineering', 143);
insert into Department (idDepartment, department_name, idFaculty) values (465, 'Sports Nutrition', 487);
insert into Department (idDepartment, department_name, idFaculty) values (466, 'Quantum Mechanics', 471);
insert into Department (idDepartment, department_name, idFaculty) values (467, 'Business Administration', 139);
insert into Department (idDepartment, department_name, idFaculty) values (468, 'Chemistry', 370);
insert into Department (idDepartment, department_name, idFaculty) values (469, 'Ancient History', 275);
insert into Department (idDepartment, department_name, idFaculty) values (470, 'Urban Sociology', 455);
insert into Department (idDepartment, department_name, idFaculty) values (471, 'Geology', 192);
insert into Department (idDepartment, department_name, idFaculty) values (472, 'English Literature', 321);
insert into Department (idDepartment, department_name, idFaculty) values (473, 'Sculpture', 76);
insert into Department (idDepartment, department_name, idFaculty) values (474, 'Business Administration', 266);
insert into Department (idDepartment, department_name, idFaculty) values (475, 'American Literature', 391);
insert into Department (idDepartment, department_name, idFaculty) values (476, 'Fine Arts', 244);
insert into Department (idDepartment, department_name, idFaculty) values (477, 'Graphic Design', 242);
insert into Department (idDepartment, department_name, idFaculty) values (478, 'Pediatric Nursing', 250);
insert into Department (idDepartment, department_name, idFaculty) values (479, 'History', 162);
insert into Department (idDepartment, department_name, idFaculty) values (480, 'Global Health', 60);
insert into Department (idDepartment, department_name, idFaculty) values (481, 'Business Administration', 122);
insert into Department (idDepartment, department_name, idFaculty) values (482, 'Cultural Studies', 198);
insert into Department (idDepartment, department_name, idFaculty) values (483, 'Counseling', 57);
insert into Department (idDepartment, department_name, idFaculty) values (484, 'Film Studies', 155);
insert into Department (idDepartment, department_name, idFaculty) values (485, 'Foreign Languages', 464);
insert into Department (idDepartment, department_name, idFaculty) values (486, 'Chemistry', 74);
insert into Department (idDepartment, department_name, idFaculty) values (487, 'Education', 314);
insert into Department (idDepartment, department_name, idFaculty) values (488, 'Polymer Chemistry', 455);
insert into Department (idDepartment, department_name, idFaculty) values (489, 'Special Education', 1);
insert into Department (idDepartment, department_name, idFaculty) values (490, 'Renewable Energy Engineering', 37);
insert into Department (idDepartment, department_name, idFaculty) values (491, 'Veterinary Science', 203);
insert into Department (idDepartment, department_name, idFaculty) values (492, 'Geography', 390);
insert into Department (idDepartment, department_name, idFaculty) values (493, 'Philosophy', 24);
insert into Department (idDepartment, department_name, idFaculty) values (494, 'Global Health', 124);
insert into Department (idDepartment, department_name, idFaculty) values (495, 'Psychology', 473);
insert into Department (idDepartment, department_name, idFaculty) values (496, 'Marketing', 410);
insert into Department (idDepartment, department_name, idFaculty) values (497, 'Crop Science', 465);
insert into Department (idDepartment, department_name, idFaculty) values (498, 'Artificial Intelligence', 131);
insert into Department (idDepartment, department_name, idFaculty) values (499, 'Electrical Engineering', 218);
insert into Department (idDepartment, department_name, idFaculty) values (500, 'Geology', 202);
insert into Department (idDepartment, department_name, idFaculty) values (501, 'Ethics', 188);
insert into Department (idDepartment, department_name, idFaculty) values (502, 'Biology', 274);
insert into Department (idDepartment, department_name, idFaculty) values (503, 'Environmental Science', 326);
insert into Department (idDepartment, department_name, idFaculty) values (504, 'Global Health', 94);
insert into Department (idDepartment, department_name, idFaculty) values (505, 'Materials Science', 160);
insert into Department (idDepartment, department_name, idFaculty) values (506, 'Nutrition', 238);
insert into Department (idDepartment, department_name, idFaculty) values (507, 'Nursing', 291);
insert into Department (idDepartment, department_name, idFaculty) values (508, 'Political Science', 78);
insert into Department (idDepartment, department_name, idFaculty) values (509, 'Music', 263);
insert into Department (idDepartment, department_name, idFaculty) values (510, 'International Relations', 32);
insert into Department (idDepartment, department_name, idFaculty) values (511, 'Pediatric Nursing', 77);
insert into Department (idDepartment, department_name, idFaculty) values (512, 'Cognitive Psychology', 330);
insert into Department (idDepartment, department_name, idFaculty) values (513, 'Urban Planning', 34);
insert into Department (idDepartment, department_name, idFaculty) values (514, 'Chemistry', 114);
insert into Department (idDepartment, department_name, idFaculty) values (515, 'Molecular Biology', 466);
insert into Department (idDepartment, department_name, idFaculty) values (516, 'Moral Philosophy', 195);
insert into Department (idDepartment, department_name, idFaculty) values (517, 'Quantum Mechanics', 331);
insert into Department (idDepartment, department_name, idFaculty) values (518, 'Foreign Languages', 76);
insert into Department (idDepartment, department_name, idFaculty) values (519, 'Quantum Mechanics', 43);
insert into Department (idDepartment, department_name, idFaculty) values (520, 'Biomedical Engineering', 321);
insert into Department (idDepartment, department_name, idFaculty) values (521, 'Physics', 35);
insert into Department (idDepartment, department_name, idFaculty) values (522, 'Mechanical Engineering', 129);
insert into Department (idDepartment, department_name, idFaculty) values (523, 'Social Work', 74);
insert into Department (idDepartment, department_name, idFaculty) values (524, 'Aerospace Engineering', 171);
insert into Department (idDepartment, department_name, idFaculty) values (525, 'Global Health', 223);
insert into Department (idDepartment, department_name, idFaculty) values (526, 'Ethics', 137);
insert into Department (idDepartment, department_name, idFaculty) values (527, 'Film Studies', 284);
insert into Department (idDepartment, department_name, idFaculty) values (528, 'Pediatric Nursing', 381);
insert into Department (idDepartment, department_name, idFaculty) values (529, 'International Relations', 303);
insert into Department (idDepartment, department_name, idFaculty) values (530, 'Electrical Engineering', 390);
insert into Department (idDepartment, department_name, idFaculty) values (531, 'Astrophysics', 488);
insert into Department (idDepartment, department_name, idFaculty) values (532, 'Artificial Intelligence', 224);
insert into Department (idDepartment, department_name, idFaculty) values (533, 'Sports Science', 350);
insert into Department (idDepartment, department_name, idFaculty) values (534, 'Cryptography', 304);
insert into Department (idDepartment, department_name, idFaculty) values (535, 'Electrical Engineering', 299);
insert into Department (idDepartment, department_name, idFaculty) values (536, 'Sustainable Architecture', 348);
insert into Department (idDepartment, department_name, idFaculty) values (537, 'Volcanology', 338);
insert into Department (idDepartment, department_name, idFaculty) values (538, 'Architecture', 267);
insert into Department (idDepartment, department_name, idFaculty) values (539, 'Sculpture', 453);
insert into Department (idDepartment, department_name, idFaculty) values (540, 'Forensic Science', 113);
insert into Department (idDepartment, department_name, idFaculty) values (541, 'Graphic Design', 202);
insert into Department (idDepartment, department_name, idFaculty) values (542, 'Cultural Studies', 1);
insert into Department (idDepartment, department_name, idFaculty) values (543, 'Cognitive Psychology', 462);
insert into Department (idDepartment, department_name, idFaculty) values (544, 'Drama', 278);
insert into Department (idDepartment, department_name, idFaculty) values (545, 'Social Work', 485);
insert into Department (idDepartment, department_name, idFaculty) values (546, 'Counseling', 367);
insert into Department (idDepartment, department_name, idFaculty) values (547, 'Business Administration', 224);
insert into Department (idDepartment, department_name, idFaculty) values (548, 'Special Education', 381);
insert into Department (idDepartment, department_name, idFaculty) values (549, 'American Literature', 434);
insert into Department (idDepartment, department_name, idFaculty) values (550, 'Organic Chemistry', 225);
