insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (1, 'Doctorate', 'Museum Studies', '0 years', 133);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (2, 'Doctorate', 'Creative Nonfiction Writing', '9 years', 292);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (3, 'Undergraduate', '19th Century American Literature', '6 years', 428);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (4, 'Undergraduate', 'Epidemiology', '7 years', 536);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (5, 'Doctorate', 'Organic Chemistry', '5 years', 113);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (6, 'Graduate', 'Cinema Studies', '6 years', 412);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (7, 'Graduate', 'Medieval Literature', '2 years', 253);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (8, 'Graduate', 'Pediatric Oncology', '3 years', 518);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (9, 'Graduate', 'Journalism and Media Studies', '8 years', 375);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (10, 'Doctorate', 'Human Resource Development', '7 years', 12);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (11, 'Graduate', 'Community Development', '8 years', 497);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (12, 'Graduate', 'Human Resource Development', '0 years', 23);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (13, 'Undergraduate', 'Art Therapy', '0 years', 130);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (14, 'Undergraduate', 'Molecular Genetics', '7 years', 447);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (15, 'Doctorate', 'Corporate Social Responsibility', '9 years', 232);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (16, 'Undergraduate', 'Cinema Studies', '3 years', 113);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (17, 'Graduate', 'Theatre Production and Design', '0 years', 129);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (18, 'Doctorate', 'Film Production', '0 years', 133);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (19, 'Undergraduate', 'Stem Cell Biology', '8 years', 46);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (20, 'Undergraduate', 'Climate Change Policy', '9 years', 235);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (21, 'Graduate', 'Behavioral Economics', '4 years', 9);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (22, 'Graduate', 'Neuropsychology', '6 years', 102);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (23, 'Doctorate', 'Environmental Policy', '2 years', 7);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (24, 'Graduate', 'Contemporary Art History', '4 years', 508);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (25, 'Undergraduate', 'Quantum Mechanics', '3 years', 60);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (26, 'Undergraduate', '19th Century American Literature', '3 years', 98);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (27, 'Graduate', 'Computational Neuroscience', '1 years', 225);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (28, 'Graduate', 'Entrepreneurship and Innovation', '2 years', 262);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (29, 'Graduate', 'Child and Adolescent Psychiatry', '1 years', 232);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (30, 'Doctorate', 'Game Design and Development', '0 years', 66);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (31, 'Doctorate', 'Tropical Ecology', '9 years', 488);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (32, 'Graduate', 'Molecular Genetics', '6 years', 422);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (33, 'Graduate', 'User Experience Design', '3 years', 78);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (34, 'Undergraduate', 'Theatre Production and Design', '5 years', 511);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (35, 'Undergraduate', 'Global Health', '4 years', 314);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (36, 'Graduate', 'Sustainable Tourism', '9 years', 271);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (37, 'Undergraduate', 'Marine Geology', '6 years', 473);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (38, 'Doctorate', 'Cinema Studies', '8 years', 264);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (39, 'Doctorate', 'Religious Ethics', '5 years', 5);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (40, 'Doctorate', 'Sports Nutrition', '3 years', 321);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (41, 'Doctorate', 'Bioinformatics', '6 years', 80);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (42, 'Graduate', 'Archaeological Anthropology', '3 years', 114);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (43, 'Undergraduate', 'Cultural Anthropology', '1 years', 134);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (44, 'Doctorate', 'Indigenous Studies', '9 years', 183);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (45, 'Undergraduate', 'Rehabilitation Counseling', '3 years', 411);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (46, 'Doctorate', 'Renewable Energy Engineering', '7 years', 317);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (47, 'Doctorate', 'Quantum Computing', '8 years', 314);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (48, 'Undergraduate', 'Community Development', '9 years', 385);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (49, 'Graduate', 'Agronomy and Crop Science', '0 years', 363);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (50, 'Undergraduate', 'Tropical Ecology', '0 years', 124);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (51, 'Undergraduate', 'Cybersecurity Policy', '4 years', 85);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (52, 'Undergraduate', 'Renewable Energy Engineering', '3 years', 371);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (53, 'Graduate', 'Astrophysics', '9 years', 109);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (54, 'Undergraduate', 'Urban Sociology', '6 years', 150);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (55, 'Undergraduate', 'Astrophysics', '9 years', 203);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (56, 'Graduate', 'Neuropsychology', '1 years', 240);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (57, 'Doctorate', 'Sculpture and Ceramics', '1 years', 69);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (58, 'Doctorate', 'Global Health', '5 years', 534);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (59, 'Undergraduate', 'Bioinformatics', '0 years', 405);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (60, 'Graduate', 'Neuropsychology', '7 years', 228);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (61, 'Doctorate', 'Renewable Energy Policy', '9 years', 362);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (62, 'Undergraduate', 'Aerospace Engineering', '6 years', 28);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (63, 'Undergraduate', 'Ethnomusicology', '8 years', 529);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (64, 'Undergraduate', 'Music Education', '0 years', 479);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (65, 'Graduate', 'Neurobiology', '2 years', 371);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (66, 'Doctorate', 'Organic Chemistry', '8 years', 386);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (67, 'Undergraduate', 'Behavioral Economics', '2 years', 57);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (68, 'Undergraduate', 'Urban Sociology', '1 years', 33);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (69, 'Doctorate', 'Industrial Design Engineering', '1 years', 331);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (70, 'Graduate', 'Urban Economics', '7 years', 30);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (71, 'Graduate', 'Quantum Computing', '8 years', 180);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (72, 'Doctorate', 'Investment Banking', '7 years', 405);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (73, 'Graduate', 'Geopolitics', '5 years', 543);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (74, 'Graduate', 'Climate Change Policy', '0 years', 421);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (75, 'Doctorate', 'Renewable Energy Policy', '9 years', 483);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (76, 'Undergraduate', 'Volcanology', '9 years', 481);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (77, 'Undergraduate', 'Music Therapy', '8 years', 430);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (78, 'Graduate', 'Journalism and Media Studies', '5 years', 394);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (79, 'Undergraduate', 'Industrial Design Engineering', '0 years', 160);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (80, 'Undergraduate', 'Rehabilitation Counseling', '7 years', 531);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (81, 'Undergraduate', 'Cognitive Psychology', '8 years', 421);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (82, 'Undergraduate', 'Geopolitics', '9 years', 319);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (83, 'Undergraduate', 'Entrepreneurship and Innovation', '5 years', 332);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (84, 'Graduate', 'Business Analytics', '3 years', 451);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (85, 'Doctorate', 'Bioinformatics', '4 years', 384);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (86, 'Undergraduate', 'Astrophysics', '9 years', 430);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (87, 'Graduate', 'Renewable Energy Engineering', '6 years', 184);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (88, 'Doctorate', 'Exercise Physiology', '3 years', 128);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (89, 'Graduate', 'International Relations', '4 years', 4);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (90, 'Graduate', 'Theatre Production and Design', '3 years', 88);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (91, 'Graduate', 'Renewable Energy Policy', '0 years', 536);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (92, 'Doctorate', 'Cognitive Neuroscience', '2 years', 465);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (93, 'Graduate', 'Art Therapy', '4 years', 427);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (94, 'Doctorate', 'Organic Chemistry', '0 years', 511);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (95, 'Doctorate', 'Political Journalism', '9 years', 78);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (96, 'Graduate', 'Cinema Studies', '6 years', 212);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (97, 'Undergraduate', 'Volcanology', '2 years', 92);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (98, 'Undergraduate', 'Urban Sociology', '0 years', 379);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (99, 'Doctorate', 'Veterinary Pathology', '7 years', 240);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (100, 'Undergraduate', 'Web Design and Development', '4 years', 188);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (101, 'Undergraduate', 'Urban Sociology', '9 years', 45);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (102, 'Undergraduate', 'Web Design and Development', '9 years', 107);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (103, 'Undergraduate', 'Music Education', '1 years', 38);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (104, 'Doctorate', 'Contemporary Art History', '0 years', 249);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (105, 'Undergraduate', 'Sustainable Tourism', '2 years', 406);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (106, 'Doctorate', 'Religious Ethics', '5 years', 486);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (107, 'Doctorate', 'Behavioral Economics', '7 years', 420);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (108, 'Graduate', 'Corporate Social Responsibility', '1 years', 122);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (109, 'Doctorate', 'Religious Ethics', '3 years', 82);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (110, 'Graduate', 'Aerospace Engineering', '7 years', 31);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (111, 'Graduate', 'Wildlife Conservation', '6 years', 192);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (112, 'Doctorate', 'Human Resource Development', '6 years', 97);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (113, 'Doctorate', 'Museum Studies', '8 years', 266);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (114, 'Undergraduate', 'Corporate Social Responsibility', '8 years', 185);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (115, 'Doctorate', 'Behavioral Economics', '4 years', 68);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (116, 'Doctorate', 'Web Design and Development', '2 years', 447);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (117, 'Undergraduate', 'Creative Nonfiction Writing', '1 years', 531);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (118, 'Undergraduate', 'Renewable Materials Engineering', '5 years', 174);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (119, 'Graduate', 'Entrepreneurship and Innovation', '3 years', 39);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (120, 'Undergraduate', 'Urban Economics', '2 years', 112);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (121, 'Doctorate', 'Archaeological Anthropology', '1 years', 463);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (122, 'Doctorate', 'Journalism and Media Studies', '4 years', 107);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (123, 'Graduate', 'Web Design and Development', '1 years', 157);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (124, 'Undergraduate', 'Pediatric Oncology', '1 years', 372);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (125, 'Graduate', 'Artificial Intelligence and Robotics', '4 years', 514);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (126, 'Undergraduate', 'Astrophysics', '8 years', 79);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (127, 'Graduate', 'Asian Literature', '9 years', 380);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (128, 'Graduate', 'Geriatric Medicine', '7 years', 215);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (129, 'Undergraduate', 'Volcanology', '5 years', 381);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (130, 'Undergraduate', 'Ethics and Moral Philosophy', '8 years', 30);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (131, 'Doctorate', 'Cognitive Psychology', '0 years', 45);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (132, 'Undergraduate', '19th Century American Literature', '7 years', 89);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (133, 'Doctorate', 'Environmental Policy', '5 years', 398);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (134, 'Graduate', 'Asian Literature', '1 years', 99);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (135, 'Graduate', 'Asian Literature', '8 years', 427);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (136, 'Graduate', 'Political Economy', '9 years', 101);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (137, 'Doctorate', 'Entrepreneurship and Innovation', '4 years', 413);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (138, 'Graduate', 'Brand Management', '9 years', 100);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (139, 'Graduate', 'Asian Literature', '2 years', 411);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (140, 'Doctorate', 'Linguistic Anthropology', '0 years', 253);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (141, 'Graduate', 'Theatre Production and Design', '6 years', 44);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (142, 'Undergraduate', 'Virtual Reality Development', '6 years', 384);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (143, 'Graduate', 'Screenwriting', '1 years', 253);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (144, 'Undergraduate', 'Religious Ethics', '7 years', 362);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (145, 'Doctorate', 'Brand Management', '0 years', 276);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (146, 'Undergraduate', 'Renewable Materials Engineering', '7 years', 183);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (147, 'Undergraduate', 'Quantum Computing', '9 years', 322);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (148, 'Undergraduate', 'Marine Geology', '5 years', 442);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (149, 'Graduate', 'Screenwriting', '3 years', 538);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (150, 'Graduate', 'Investment Banking', '5 years', 310);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (151, 'Doctorate', 'Creative Nonfiction Writing', '2 years', 176);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (152, 'Doctorate', 'Cinema Studies', '5 years', 24);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (153, 'Graduate', 'Comparative Literature', '8 years', 405);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (154, 'Graduate', 'Organic Chemistry', '5 years', 206);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (155, 'Graduate', 'Structural Engineering', '7 years', 61);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (156, 'Undergraduate', 'Investment Banking', '4 years', 51);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (157, 'Undergraduate', 'Poetry Writing', '5 years', 117);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (158, 'Undergraduate', 'Behavioral Economics', '1 years', 102);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (159, 'Doctorate', 'Brand Management', '3 years', 20);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (160, 'Undergraduate', 'Music Therapy', '0 years', 378);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (161, 'Graduate', 'Human Resource Development', '0 years', 283);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (162, 'Doctorate', 'Human Genetics', '6 years', 169);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (163, 'Graduate', 'Molecular Biology', '2 years', 131);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (164, 'Doctorate', 'Sustainable Tourism', '9 years', 479);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (165, 'Doctorate', 'Oceanography', '7 years', 530);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (166, 'Graduate', 'Renewable Materials Engineering', '4 years', 507);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (167, 'Undergraduate', 'Behavioral Finance', '2 years', 128);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (168, 'Graduate', 'Bioinformatics', '7 years', 466);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (169, 'Graduate', 'Cybersecurity Policy', '3 years', 108);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (170, 'Undergraduate', 'Artificial Intelligence and Robotics', '9 years', 537);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (171, 'Doctorate', 'Forensic Psychology', '1 years', 488);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (172, 'Graduate', 'Organic Chemistry', '9 years', 111);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (173, 'Graduate', 'Neuropsychology', '2 years', 178);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (174, 'Graduate', 'Film Production', '1 years', 499);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (175, 'Graduate', 'Ethics and Moral Philosophy', '6 years', 298);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (176, 'Doctorate', 'Theatre Production and Design', '3 years', 340);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (177, 'Graduate', 'Corporate Social Responsibility', '3 years', 383);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (178, 'Graduate', 'Ancient History', '1 years', 357);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (179, 'Doctorate', 'Molecular Biology', '4 years', 350);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (180, 'Undergraduate', 'Conflict Resolution', '1 years', 301);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (181, 'Doctorate', 'Medieval Literature', '1 years', 103);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (182, 'Undergraduate', 'Sustainable Architecture', '4 years', 101);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (183, 'Undergraduate', 'Aerospace Engineering', '0 years', 435);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (184, 'Graduate', 'Renewable Materials Engineering', '0 years', 166);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (185, 'Undergraduate', 'Sculpture and Ceramics', '7 years', 319);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (186, 'Graduate', 'Asian Literature', '8 years', 520);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (187, 'Undergraduate', 'Islamic Studies', '0 years', 271);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (188, 'Graduate', 'Art Conservation', '3 years', 178);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (189, 'Undergraduate', 'Pediatric Nursing', '1 years', 348);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (190, 'Undergraduate', 'Ancient History', '2 years', 493);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (191, 'Undergraduate', 'Medieval Literature', '3 years', 438);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (192, 'Graduate', 'Veterinary Pathology', '7 years', 389);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (193, 'Graduate', 'Quantum Computing', '9 years', 199);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (194, 'Doctorate', 'Film Production', '0 years', 452);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (195, 'Undergraduate', 'Renewable Energy Engineering', '8 years', 154);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (196, 'Undergraduate', 'Rehabilitation Counseling', '3 years', 158);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (197, 'Undergraduate', 'Human Resource Development', '8 years', 412);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (198, 'Undergraduate', 'Forensic Psychology', '3 years', 173);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (199, 'Doctorate', '19th Century American Literature', '4 years', 474);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (200, 'Undergraduate', 'Oceanography', '4 years', 25);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (201, 'Graduate', 'Neurobiology', '0 years', 47);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (202, 'Undergraduate', 'Cognitive Neuroscience', '1 years', 193);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (203, 'Doctorate', 'Ethnomusicology', '7 years', 96);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (204, 'Undergraduate', '19th Century American Literature', '1 years', 412);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (205, 'Doctorate', 'Political Economy', '8 years', 181);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (206, 'Undergraduate', 'Computational Linguistics', '3 years', 347);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (207, 'Undergraduate', 'Sustainable Tourism', '5 years', 190);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (208, 'Undergraduate', 'Renewable Materials Engineering', '2 years', 235);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (209, 'Doctorate', 'Investment Banking', '2 years', 202);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (210, 'Doctorate', 'Poetry Writing', '8 years', 316);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (211, 'Graduate', 'Brand Management', '6 years', 195);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (212, 'Undergraduate', 'Art Therapy', '0 years', 46);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (213, 'Graduate', 'Cognitive Neuroscience', '2 years', 95);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (214, 'Graduate', 'Cryptography and Network Security', '0 years', 83);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (215, 'Graduate', 'Pediatric Nursing', '4 years', 498);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (216, 'Undergraduate', 'Stem Cell Biology', '8 years', 182);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (217, 'Undergraduate', 'Tropical Ecology', '0 years', 434);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (218, 'Graduate', 'Urban Sociology', '0 years', 505);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (219, 'Graduate', 'Asian Literature', '5 years', 267);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (220, 'Undergraduate', 'Oceanography', '1 years', 345);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (221, 'Undergraduate', 'Art Therapy', '7 years', 422);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (222, 'Graduate', 'Asian Literature', '3 years', 474);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (223, 'Graduate', 'Environmental Policy', '5 years', 537);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (224, 'Doctorate', 'Asian Literature', '6 years', 483);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (225, 'Graduate', 'Contemporary Art History', '4 years', 544);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (226, 'Doctorate', 'Cybersecurity Policy', '9 years', 519);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (227, 'Graduate', 'Renewable Energy Engineering', '1 years', 197);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (228, 'Undergraduate', 'Religious Ethics', '0 years', 348);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (229, 'Doctorate', 'Computational Neuroscience', '8 years', 318);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (230, 'Undergraduate', 'International Relations', '9 years', 31);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (231, 'Doctorate', 'Urban Economics', '6 years', 462);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (232, 'Graduate', 'Plant Biotechnology', '8 years', 230);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (233, 'Undergraduate', 'Sports Nutrition', '0 years', 167);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (234, 'Graduate', 'Public Policy Analysis', '0 years', 332);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (235, 'Graduate', 'Neurobiology', '9 years', 238);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (236, 'Graduate', 'International Relations', '6 years', 342);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (237, 'Doctorate', 'Cognitive Psychology', '5 years', 21);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (238, 'Undergraduate', 'Neuropsychology', '0 years', 140);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (239, 'Doctorate', 'Agronomy and Crop Science', '2 years', 254);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (240, 'Undergraduate', 'Conflict Resolution', '6 years', 51);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (241, 'Graduate', 'Sports Nutrition', '8 years', 323);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (242, 'Graduate', 'Quantum Computing', '5 years', 264);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (243, 'Undergraduate', 'Web Design and Development', '7 years', 528);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (244, 'Undergraduate', 'Cognitive Psychology', '8 years', 215);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (245, 'Undergraduate', 'Child and Adolescent Psychiatry', '5 years', 179);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (246, 'Graduate', 'Epidemiology', '3 years', 318);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (247, 'Doctorate', 'Cybersecurity Policy', '6 years', 389);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (248, 'Doctorate', '19th Century American Literature', '2 years', 243);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (249, 'Undergraduate', 'Brand Management', '1 years', 544);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (250, 'Undergraduate', 'Cryptography and Network Security', '3 years', 107);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (251, 'Graduate', '19th Century American Literature', '7 years', 40);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (252, 'Doctorate', 'Computational Linguistics', '2 years', 355);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (253, 'Undergraduate', 'Urban Sociology', '0 years', 228);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (254, 'Graduate', 'Indigenous Studies', '7 years', 548);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (255, 'Doctorate', 'Entrepreneurship and Innovation', '2 years', 378);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (256, 'Graduate', 'Art Conservation', '2 years', 30);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (257, 'Doctorate', 'Quantum Mechanics', '4 years', 456);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (258, 'Doctorate', 'Quantum Mechanics', '2 years', 414);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (259, 'Undergraduate', 'Sports Nutrition', '9 years', 222);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (260, 'Doctorate', 'Art Conservation', '3 years', 374);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (261, 'Undergraduate', 'Volcanology', '4 years', 326);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (262, 'Undergraduate', 'Political Economy', '4 years', 334);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (263, 'Undergraduate', 'Molecular Genetics', '4 years', 408);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (264, 'Undergraduate', 'Ethics and Moral Philosophy', '5 years', 138);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (265, 'Graduate', 'Behavioral Economics', '4 years', 14);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (266, 'Undergraduate', 'Quantum Mechanics', '0 years', 391);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (267, 'Undergraduate', 'Ethics and Moral Philosophy', '2 years', 384);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (268, 'Graduate', 'Urban Sociology', '1 years', 434);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (269, 'Graduate', 'Ethnomusicology', '5 years', 143);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (270, 'Undergraduate', 'Pediatric Oncology', '1 years', 220);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (271, 'Undergraduate', 'Ethnomusicology', '0 years', 28);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (272, 'Graduate', 'Astrophysics', '5 years', 228);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (273, 'Graduate', 'Contemporary Dance', '8 years', 469);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (274, 'Graduate', 'Organic Chemistry', '2 years', 265);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (275, 'Graduate', 'Structural Engineering', '2 years', 100);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (276, 'Doctorate', 'User Experience Design', '1 years', 477);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (277, 'Graduate', 'Special Education', '9 years', 286);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (278, 'Undergraduate', 'Music Therapy', '8 years', 36);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (279, 'Graduate', 'Climate Change Policy', '6 years', 17);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (280, 'Doctorate', 'Asian Literature', '3 years', 188);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (281, 'Doctorate', 'Archaeological Anthropology', '7 years', 520);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (282, 'Undergraduate', 'Archaeological Anthropology', '4 years', 210);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (283, 'Undergraduate', 'Business Analytics', '5 years', 417);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (284, 'Doctorate', 'Agronomy and Crop Science', '8 years', 191);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (285, 'Undergraduate', 'Comparative Literature', '7 years', 395);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (286, 'Doctorate', 'Oceanography', '8 years', 90);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (287, 'Undergraduate', 'Music Therapy', '5 years', 488);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (288, 'Doctorate', 'Contemporary Art History', '7 years', 503);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (289, 'Graduate', 'Corporate Social Responsibility', '0 years', 413);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (290, 'Undergraduate', 'Journalism and Media Studies', '9 years', 54);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (291, 'Graduate', 'Corporate Social Responsibility', '3 years', 44);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (292, 'Doctorate', 'Neurobiology', '7 years', 206);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (293, 'Graduate', 'Theatre Production and Design', '8 years', 51);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (294, 'Undergraduate', 'Stem Cell Biology', '3 years', 208);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (295, 'Undergraduate', 'Special Education', '7 years', 219);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (296, 'Undergraduate', 'Sustainable Agriculture', '9 years', 450);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (297, 'Doctorate', 'Cryptography and Network Security', '5 years', 113);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (298, 'Doctorate', 'Behavioral Economics', '1 years', 63);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (299, 'Undergraduate', 'Global Health', '1 years', 124);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (300, 'Doctorate', 'Renewable Energy Engineering', '9 years', 36);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (301, 'Undergraduate', 'Plant Biotechnology', '5 years', 357);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (302, 'Graduate', 'Stem Cell Biology', '1 years', 405);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (303, 'Undergraduate', 'Museum Studies', '2 years', 391);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (304, 'Doctorate', 'Urban Economics', '4 years', 68);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (305, 'Doctorate', 'Corporate Social Responsibility', '6 years', 165);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (306, 'Graduate', 'Public Policy Analysis', '7 years', 182);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (307, 'Doctorate', 'Archaeological Anthropology', '1 years', 371);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (308, 'Doctorate', 'Screenwriting', '0 years', 121);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (309, 'Graduate', 'Industrial Design Engineering', '9 years', 212);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (310, 'Graduate', 'Asian Literature', '5 years', 13);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (311, 'Doctorate', 'Ancient History', '3 years', 206);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (312, 'Undergraduate', 'Sustainable Tourism', '3 years', 280);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (313, 'Doctorate', 'Cognitive Psychology', '6 years', 33);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (314, 'Graduate', 'Child and Adolescent Psychiatry', '9 years', 499);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (315, 'Graduate', 'Business Analytics', '5 years', 138);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (316, 'Undergraduate', 'Pediatric Oncology', '6 years', 39);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (317, 'Undergraduate', 'Oceanography', '0 years', 410);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (318, 'Graduate', 'Epidemiology', '3 years', 483);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (319, 'Undergraduate', 'Creative Nonfiction Writing', '8 years', 374);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (320, 'Undergraduate', 'Renewable Energy Policy', '7 years', 152);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (321, 'Undergraduate', 'Web Design and Development', '7 years', 197);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (322, 'Graduate', 'Public Policy Analysis', '4 years', 110);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (323, 'Undergraduate', 'Medieval Literature', '6 years', 465);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (324, 'Graduate', 'User Experience Design', '8 years', 506);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (325, 'Doctorate', 'Poetry Writing', '5 years', 230);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (326, 'Graduate', 'Archaeological Anthropology', '7 years', 27);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (327, 'Graduate', 'Behavioral Economics', '2 years', 98);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (328, 'Doctorate', 'Sustainable Tourism', '3 years', 201);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (329, 'Undergraduate', 'Comparative Literature', '0 years', 266);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (330, 'Graduate', 'Entrepreneurship and Innovation', '6 years', 65);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (331, 'Undergraduate', 'Cultural Anthropology', '2 years', 490);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (332, 'Doctorate', 'Web Design and Development', '8 years', 333);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (333, 'Doctorate', 'Molecular Biology', '1 years', 435);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (334, 'Doctorate', '19th Century American Literature', '8 years', 335);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (335, 'Graduate', 'Climate Change Policy', '8 years', 513);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (336, 'Doctorate', 'Asian Literature', '3 years', 373);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (337, 'Graduate', 'Political Journalism', '9 years', 470);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (338, 'Graduate', 'Quantum Computing', '1 years', 200);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (339, 'Graduate', 'Cinema Studies', '8 years', 430);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (340, 'Doctorate', 'Game Design and Development', '4 years', 399);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (341, 'Doctorate', 'Creative Nonfiction Writing', '9 years', 129);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (342, 'Doctorate', 'Ethics and Moral Philosophy', '5 years', 105);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (343, 'Doctorate', 'Geriatric Medicine', '7 years', 401);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (344, 'Doctorate', 'Neurobiology', '4 years', 35);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (345, 'Undergraduate', '19th Century American Literature', '6 years', 542);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (346, 'Graduate', 'Screenwriting', '1 years', 274);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (347, 'Doctorate', 'Brand Management', '0 years', 242);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (348, 'Undergraduate', 'Ethnomusicology', '8 years', 297);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (349, 'Doctorate', 'Screenwriting', '9 years', 134);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (350, 'Undergraduate', 'Quantum Mechanics', '6 years', 483);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (351, 'Undergraduate', 'Contemporary Dance', '4 years', 64);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (352, 'Graduate', 'Human Resource Development', '6 years', 543);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (353, 'Doctorate', 'Molecular Genetics', '9 years', 18);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (354, 'Undergraduate', 'Veterinary Pathology', '1 years', 429);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (355, 'Doctorate', 'Pediatric Nursing', '1 years', 274);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (356, 'Graduate', 'Religious Ethics', '7 years', 514);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (357, 'Graduate', 'Renewable Energy Policy', '6 years', 394);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (358, 'Graduate', 'Asian Literature', '2 years', 472);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (359, 'Undergraduate', 'Marine Geology', '6 years', 23);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (360, 'Undergraduate', 'Aerospace Engineering', '1 years', 86);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (361, 'Doctorate', 'Plant Biotechnology', '2 years', 24);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (362, 'Undergraduate', 'Bioinformatics', '6 years', 334);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (363, 'Doctorate', 'Cognitive Psychology', '6 years', 442);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (364, 'Undergraduate', 'Archaeological Anthropology', '8 years', 43);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (365, 'Undergraduate', 'Cultural Anthropology', '1 years', 168);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (366, 'Undergraduate', 'User Experience Design', '7 years', 259);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (367, 'Undergraduate', 'Geopolitics', '3 years', 176);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (368, 'Doctorate', 'Renewable Materials Engineering', '5 years', 186);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (369, 'Graduate', 'Cognitive Psychology', '9 years', 99);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (370, 'Doctorate', 'Oceanography', '4 years', 179);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (371, 'Doctorate', 'Political Journalism', '2 years', 108);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (372, 'Undergraduate', 'Human Resource Development', '8 years', 541);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (373, 'Undergraduate', 'Computational Linguistics', '4 years', 99);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (374, 'Doctorate', 'Game Design and Development', '7 years', 521);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (375, 'Undergraduate', 'Structural Engineering', '0 years', 377);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (376, 'Undergraduate', 'Game Design and Development', '6 years', 89);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (377, 'Undergraduate', 'Forensic Psychology', '0 years', 30);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (378, 'Graduate', 'Behavioral Finance', '9 years', 475);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (379, 'Graduate', 'Art Conservation', '9 years', 323);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (380, 'Graduate', 'Cognitive Psychology', '6 years', 484);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (381, 'Undergraduate', 'Human Genetics', '0 years', 61);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (382, 'Undergraduate', 'Exercise Physiology', '4 years', 40);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (383, 'Doctorate', 'Diplomatic Studies', '1 years', 219);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (384, 'Doctorate', 'Cognitive Neuroscience', '1 years', 221);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (385, 'Undergraduate', 'Environmental Chemistry', '1 years', 104);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (386, 'Doctorate', 'Molecular Biology', '0 years', 512);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (387, 'Doctorate', 'Neurobiology', '4 years', 379);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (388, 'Undergraduate', 'Contemporary Dance', '6 years', 249);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (389, 'Doctorate', 'Volcanology', '1 years', 278);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (390, 'Graduate', 'Climate Change Policy', '4 years', 399);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (391, 'Doctorate', 'Islamic Studies', '3 years', 86);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (392, 'Doctorate', 'Brand Management', '8 years', 410);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (393, 'Undergraduate', 'Renewable Energy Engineering', '1 years', 172);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (394, 'Graduate', 'Cryptography and Network Security', '6 years', 61);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (395, 'Doctorate', 'Entrepreneurship and Innovation', '5 years', 344);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (396, 'Graduate', 'Theatre Production and Design', '3 years', 104);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (397, 'Graduate', 'Sculpture and Ceramics', '5 years', 508);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (398, 'Undergraduate', 'Computational Linguistics', '7 years', 231);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (399, 'Graduate', 'Sculpture and Ceramics', '3 years', 114);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (400, 'Graduate', 'Cognitive Psychology', '0 years', 384);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (401, 'Undergraduate', 'Pediatric Nursing', '7 years', 422);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (402, 'Undergraduate', 'Investment Banking', '9 years', 153);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (403, 'Graduate', 'Investment Banking', '0 years', 61);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (404, 'Graduate', 'Screenwriting', '1 years', 493);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (405, 'Graduate', 'Web Design and Development', '6 years', 393);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (406, 'Doctorate', 'Creative Nonfiction Writing', '9 years', 303);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (407, 'Graduate', 'Indigenous Studies', '1 years', 347);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (408, 'Doctorate', 'Pediatric Oncology', '0 years', 545);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (409, 'Graduate', 'Molecular Biology', '0 years', 409);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (410, 'Doctorate', 'Oceanography', '1 years', 37);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (411, 'Doctorate', 'Agronomy and Crop Science', '1 years', 525);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (412, 'Graduate', 'Molecular Genetics', '3 years', 526);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (413, 'Doctorate', 'Tropical Ecology', '4 years', 169);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (414, 'Doctorate', 'Computational Linguistics', '0 years', 37);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (415, 'Undergraduate', 'Museum Studies', '7 years', 169);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (416, 'Undergraduate', 'Behavioral Finance', '0 years', 144);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (417, 'Undergraduate', 'Creative Nonfiction Writing', '1 years', 356);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (418, 'Graduate', 'Forensic Psychology', '7 years', 104);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (419, 'Undergraduate', 'Quantum Computing', '0 years', 513);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (420, 'Graduate', 'Sustainable Architecture', '5 years', 493);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (421, 'Undergraduate', 'Artificial Intelligence and Robotics', '5 years', 339);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (422, 'Graduate', 'Community Development', '5 years', 170);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (423, 'Doctorate', 'Urban Economics', '3 years', 399);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (424, 'Doctorate', 'Artificial Intelligence and Robotics', '2 years', 249);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (425, 'Undergraduate', 'Cognitive Neuroscience', '6 years', 458);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (426, 'Undergraduate', 'Neuropsychology', '4 years', 73);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (427, 'Undergraduate', 'Journalism and Media Studies', '9 years', 505);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (428, 'Doctorate', 'Molecular Genetics', '6 years', 24);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (429, 'Doctorate', 'Virtual Reality Development', '9 years', 101);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (430, 'Doctorate', 'Computational Neuroscience', '7 years', 440);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (431, 'Doctorate', 'Veterinary Pathology', '9 years', 157);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (432, 'Undergraduate', 'Archaeological Anthropology', '8 years', 218);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (433, 'Doctorate', 'Music Education', '8 years', 81);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (434, 'Doctorate', 'Environmental Chemistry', '1 years', 32);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (435, 'Doctorate', 'Ethnomusicology', '1 years', 328);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (436, 'Undergraduate', 'Tropical Ecology', '0 years', 484);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (437, 'Undergraduate', 'Computational Neuroscience', '3 years', 80);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (438, 'Undergraduate', 'Child and Adolescent Psychiatry', '4 years', 479);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (439, 'Graduate', 'Organic Chemistry', '7 years', 60);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (440, 'Graduate', 'Molecular Genetics', '8 years', 389);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (441, 'Doctorate', 'Human Genetics', '4 years', 276);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (442, 'Undergraduate', 'Quantum Mechanics', '4 years', 223);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (443, 'Undergraduate', 'Asian Literature', '7 years', 482);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (444, 'Graduate', 'Human Resource Development', '3 years', 54);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (445, 'Doctorate', 'Sustainable Architecture', '7 years', 352);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (446, 'Undergraduate', 'Corporate Social Responsibility', '9 years', 10);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (447, 'Undergraduate', 'Art Therapy', '1 years', 191);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (448, 'Doctorate', 'Polymer Chemistry', '3 years', 468);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (449, 'Doctorate', 'Volcanology', '7 years', 119);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (450, 'Undergraduate', 'Human Genetics', '6 years', 473);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (451, 'Undergraduate', 'Structural Engineering', '9 years', 492);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (452, 'Doctorate', 'Behavioral Economics', '2 years', 358);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (453, 'Doctorate', 'Computational Neuroscience', '4 years', 339);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (454, 'Graduate', 'Bioinformatics', '7 years', 357);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (455, 'Graduate', 'Global Health', '7 years', 168);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (456, 'Doctorate', 'Marine Geology', '7 years', 522);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (457, 'Graduate', 'Ancient History', '1 years', 122);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (458, 'Doctorate', 'Environmental Policy', '0 years', 498);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (459, 'Doctorate', 'Public Policy Analysis', '3 years', 310);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (460, 'Undergraduate', 'Human Genetics', '1 years', 508);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (461, 'Doctorate', 'Pediatric Nursing', '7 years', 535);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (462, 'Doctorate', 'Veterinary Pathology', '1 years', 304);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (463, 'Undergraduate', 'Public Policy Analysis', '8 years', 275);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (464, 'Undergraduate', 'Molecular Genetics', '3 years', 128);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (465, 'Undergraduate', 'User Experience Design', '6 years', 54);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (466, 'Graduate', 'Geopolitics', '9 years', 284);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (467, 'Undergraduate', 'Public Policy Analysis', '4 years', 1);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (468, 'Graduate', 'User Experience Design', '6 years', 514);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (469, 'Graduate', 'Special Education', '1 years', 65);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (470, 'Doctorate', 'Urban Economics', '3 years', 294);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (471, 'Doctorate', 'Screenwriting', '3 years', 135);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (472, 'Graduate', 'Plant Biotechnology', '6 years', 38);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (473, 'Undergraduate', 'Web Design and Development', '8 years', 270);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (474, 'Doctorate', 'Neuropsychology', '9 years', 329);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (475, 'Doctorate', 'Business Analytics', '1 years', 478);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (476, 'Undergraduate', 'Neuropsychology', '7 years', 380);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (477, 'Graduate', 'Business Analytics', '3 years', 532);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (478, 'Doctorate', 'Quantum Mechanics', '7 years', 523);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (479, 'Graduate', 'Music Therapy', '6 years', 544);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (480, 'Graduate', 'Stem Cell Biology', '9 years', 18);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (481, 'Doctorate', 'Cognitive Psychology', '8 years', 456);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (482, 'Graduate', 'Special Education', '8 years', 485);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (483, 'Doctorate', 'Exercise Physiology', '6 years', 246);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (484, 'Undergraduate', 'Astrophysics', '3 years', 314);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (485, 'Doctorate', 'User Experience Design', '6 years', 473);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (486, 'Graduate', 'Behavioral Economics', '8 years', 432);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (487, 'Undergraduate', 'Sculpture and Ceramics', '3 years', 368);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (488, 'Doctorate', 'Stem Cell Biology', '1 years', 542);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (489, 'Undergraduate', 'Religious Ethics', '2 years', 425);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (490, 'Graduate', 'Industrial Design Engineering', '3 years', 534);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (491, 'Doctorate', 'Cinema Studies', '6 years', 339);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (492, 'Doctorate', 'Religious Ethics', '7 years', 11);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (493, 'Graduate', 'Cryptography and Network Security', '8 years', 404);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (494, 'Doctorate', 'Human Resource Development', '3 years', 93);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (495, 'Graduate', 'Agronomy and Crop Science', '2 years', 335);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (496, 'Doctorate', 'Quantum Mechanics', '3 years', 386);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (497, 'Undergraduate', 'Volcanology', '4 years', 253);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (498, 'Graduate', 'Special Education', '3 years', 533);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (499, 'Graduate', 'Cinema Studies', '3 years', 246);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (500, 'Undergraduate', 'Environmental Policy', '8 years', 474);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (501, 'Graduate', 'Marine Geology', '3 years', 302);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (502, 'Doctorate', 'Creative Nonfiction Writing', '7 years', 62);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (503, 'Undergraduate', 'Cognitive Neuroscience', '2 years', 454);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (504, 'Undergraduate', 'Polymer Chemistry', '7 years', 528);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (505, 'Graduate', 'Diplomatic Studies', '6 years', 303);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (506, 'Graduate', 'Bioinformatics', '7 years', 427);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (507, 'Doctorate', 'Agronomy and Crop Science', '0 years', 345);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (508, 'Undergraduate', 'Neuropsychology', '4 years', 324);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (509, 'Graduate', 'Urban Economics', '9 years', 133);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (510, 'Graduate', 'Geopolitics', '0 years', 414);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (511, 'Undergraduate', 'Volcanology', '2 years', 334);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (512, 'Graduate', 'Indigenous Studies', '6 years', 509);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (513, 'Undergraduate', 'Web Design and Development', '7 years', 416);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (514, 'Graduate', 'Environmental Chemistry', '8 years', 202);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (515, 'Undergraduate', 'Theatre Production and Design', '0 years', 361);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (516, 'Undergraduate', 'Ethnomusicology', '9 years', 307);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (517, 'Doctorate', 'Marine Geology', '7 years', 521);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (518, 'Doctorate', 'Political Journalism', '2 years', 492);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (519, 'Doctorate', 'Renewable Energy Engineering', '3 years', 38);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (520, 'Undergraduate', 'Agronomy and Crop Science', '8 years', 177);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (521, 'Doctorate', 'Museum Studies', '7 years', 372);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (522, 'Graduate', 'Human Genetics', '9 years', 390);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (523, 'Doctorate', 'Geopolitics', '9 years', 387);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (524, 'Doctorate', 'Global Health', '7 years', 331);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (525, 'Graduate', 'Journalism and Media Studies', '4 years', 294);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (526, 'Doctorate', 'Ethnomusicology', '9 years', 264);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (527, 'Graduate', 'Cognitive Psychology', '5 years', 119);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (528, 'Graduate', 'Sustainable Tourism', '3 years', 267);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (529, 'Graduate', 'Veterinary Pathology', '1 years', 426);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (530, 'Undergraduate', 'Behavioral Finance', '1 years', 164);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (531, 'Graduate', 'Creative Nonfiction Writing', '2 years', 57);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (532, 'Doctorate', 'Exercise Physiology', '7 years', 214);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (533, 'Doctorate', 'Indigenous Studies', '3 years', 12);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (534, 'Doctorate', 'Political Journalism', '8 years', 270);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (535, 'Graduate', 'Cognitive Neuroscience', '1 years', 510);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (536, 'Graduate', 'Environmental Chemistry', '3 years', 349);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (537, 'Graduate', 'Linguistic Anthropology', '8 years', 180);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (538, 'Undergraduate', 'Contemporary Dance', '3 years', 193);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (539, 'Graduate', 'Human Resource Development', '3 years', 131);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (540, 'Graduate', 'Epidemiology', '5 years', 239);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (541, 'Undergraduate', 'Cybersecurity Policy', '9 years', 469);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (542, 'Doctorate', 'Stem Cell Biology', '6 years', 388);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (543, 'Undergraduate', 'Diplomatic Studies', '3 years', 541);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (544, 'Undergraduate', '19th Century American Literature', '1 years', 358);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (545, 'Doctorate', 'Cinema Studies', '5 years', 46);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (546, 'Undergraduate', 'Cognitive Neuroscience', '5 years', 507);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (547, 'Graduate', 'Pediatric Oncology', '5 years', 363);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (548, 'Doctorate', 'Cinema Studies', '0 years', 306);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (549, 'Undergraduate', 'Organic Chemistry', '1 years', 281);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (550, 'Doctorate', 'Cybersecurity Policy', '8 years', 70);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (551, 'Graduate', 'Polymer Chemistry', '9 years', 165);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (552, 'Doctorate', 'Linguistic Anthropology', '8 years', 305);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (553, 'Doctorate', 'Game Design and Development', '7 years', 61);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (554, 'Undergraduate', 'International Relations', '7 years', 446);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (555, 'Graduate', 'Music Education', '1 years', 332);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (556, 'Doctorate', 'Game Design and Development', '5 years', 80);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (557, 'Graduate', 'Contemporary Dance', '6 years', 206);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (558, 'Graduate', 'Agronomy and Crop Science', '7 years', 459);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (559, 'Graduate', 'Marine Geology', '0 years', 17);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (560, 'Undergraduate', 'Agronomy and Crop Science', '8 years', 340);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (561, 'Doctorate', 'Astrophysics', '3 years', 297);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (562, 'Doctorate', 'Astrophysics', '7 years', 364);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (563, 'Undergraduate', 'Agronomy and Crop Science', '4 years', 464);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (564, 'Undergraduate', 'Museum Studies', '5 years', 421);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (565, 'Graduate', 'Molecular Genetics', '9 years', 151);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (566, 'Doctorate', 'Music Education', '6 years', 87);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (567, 'Graduate', 'Environmental Chemistry', '9 years', 210);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (568, 'Graduate', 'Renewable Materials Engineering', '6 years', 522);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (569, 'Graduate', 'International Relations', '2 years', 178);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (570, 'Doctorate', 'Cultural Anthropology', '1 years', 75);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (571, 'Doctorate', 'Plant Biotechnology', '6 years', 313);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (572, 'Graduate', 'Veterinary Pathology', '6 years', 512);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (573, 'Doctorate', 'Contemporary Art History', '4 years', 113);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (574, 'Undergraduate', 'Poetry Writing', '2 years', 309);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (575, 'Doctorate', 'Art Conservation', '0 years', 525);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (576, 'Doctorate', 'Polymer Chemistry', '8 years', 462);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (577, 'Graduate', 'Contemporary Art History', '4 years', 11);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (578, 'Doctorate', 'Global Health', '1 years', 238);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (579, 'Graduate', 'Geopolitics', '2 years', 539);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (580, 'Doctorate', 'Cognitive Neuroscience', '0 years', 482);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (581, 'Doctorate', 'Behavioral Economics', '8 years', 130);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (582, 'Undergraduate', 'Computational Linguistics', '8 years', 539);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (583, 'Doctorate', 'Forensic Psychology', '4 years', 446);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (584, 'Graduate', 'Computational Linguistics', '0 years', 272);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (585, 'Doctorate', 'Behavioral Finance', '2 years', 465);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (586, 'Doctorate', 'Quantum Mechanics', '1 years', 450);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (587, 'Doctorate', 'Computational Linguistics', '4 years', 377);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (588, 'Doctorate', 'Corporate Social Responsibility', '7 years', 412);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (589, 'Graduate', 'Geriatric Medicine', '2 years', 238);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (590, 'Doctorate', 'Music Education', '6 years', 197);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (591, 'Graduate', 'Public Policy Analysis', '2 years', 104);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (592, 'Undergraduate', 'Renewable Energy Engineering', '7 years', 35);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (593, 'Undergraduate', 'Stem Cell Biology', '5 years', 229);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (594, 'Graduate', 'Quantum Mechanics', '2 years', 7);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (595, 'Doctorate', 'Plant Biotechnology', '3 years', 158);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (596, 'Graduate', 'Behavioral Economics', '3 years', 507);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (597, 'Undergraduate', 'Geriatric Medicine', '6 years', 238);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (598, 'Doctorate', 'Poetry Writing', '5 years', 464);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (599, 'Undergraduate', 'Sustainable Architecture', '2 years', 307);
insert into Program (idProgram, academic_lvl, program_name, duration, idDepartment) values (600, 'Graduate', 'Virtual Reality Development', '5 years', 276);
